.gitignore
There is currently only one `.gitignore` on tools/app.
Git ignore file should be on root level so that it affects the whole repository.
FYI: @samilempinen @henryhaverinen
=> Use root level .gitignore file

examples/decision-records/.cards/local/workflows/decision-workflow.json, tools/app/__tests__/components.test.tsx, tools/app/app/components/StateSelector.tsx, tools/data-handler/src/interfaces/project-interfaces.ts, tools/data-handler/test/test-data/invalid/invalid-card-has-wrong-state/.cards/local/workflows/decision-workflow.json, tools/data-handler/test/test-data/invalid/invalid-card-has-wrong-state/.cards/local/workflows/simple-workflow.json, tools/data-handler/test/test-data/valid/decision-records/.cards/local/workflows/decision-workflow.json, tools/data-handler/test/test-data/valid/decision-records/.cards/local/workflows/simple-workflow.json, tools/schema/workflow-schema.json
We don't have a good concept for using the "hidden" category for now.
Let's remove it until there is a clear picture how to use it.
=> INTDEV-321 Remove 'hidden' workflow category

tools/data-handler/src/command-handler.ts, tools/data-handler/src/containers/project.ts, tools/data-handler/src/rename.ts
When project prefix is changed, all of the card keys and references to them are needed to be updated.
This includes attachments and links to them from the cards. 
Unfortunately, the earlier implementation didn't fetch card details for attachments (`{attachments: true}, ...}`) when it fetched the cards for renaming. This meant that it looked like that the cards didn't have any attachments at all.
Fixed by adding `attachments: true` to the card details when they are fetched.
=> INTDEV-305 Fetch attachment details when renaming project

tools/data-handler/src/interfaces/project-interfaces.ts, tools/data-handler/src/validate.ts
Final part of card content validations: validating that the enum values are correct.
Noticed that the interface for the custom types was incorrect; fixed it in this PR as well.
Additionally, I cleaned up the output from the validations:
=> INTDEV-308 Validate enum values

package-lock.json, tools/data-handler/package.json, tools/data-handler/src/containers/project.ts, tools/data-handler/src/containers/template.ts, tools/data-handler/src/interfaces/project-interfaces.ts, tools/data-handler/src/validate.ts, tools/data-handler/test/0_validate.test.ts, tools/data-handler/test/test-data/valid/decision-records/.cards/local/cardtypes/decision-cardtype.json, tools/data-handler/test/test-data/valid/decision-records/.cards/local/fieldtypes/admins.json, tools/data-handler/test/test-data/valid/decision-records/.cards/local/fieldtypes/commit-description.json, tools/data-handler/test/test-data/valid/decision-records/.cards/local/fieldtypes/finished.json, tools/data-handler/test/test-data/valid/decision-records/.cards/local/fieldtypes/last-changed-date.json, tools/data-handler/test/test-data/valid/decision-records/.cards/local/fieldtypes/last-changed-timestamp.json, tools/data-handler/test/test-data/valid/decision-records/.cards/local/fieldtypes/number-of-commits.json, tools/data-handler/test/test-data/valid/decision-records/.cards/local/fieldtypes/percentage-ready.json, tools/data-handler/test/test-data/valid/decision-records/.cards/local/fieldtypes/responsible.json, tools/data-handler/test/test-data/valid/decision-records/cardroot/decision_5/c/decision_6/index.json
Continuation of card data validation. 
Card's custom fields are validated against types defined by "field types".
**Note** that `null` is acceptable value for all; `person` also allows for empty string. 
Additionally, fixed an issue with card creation where custom fields without values from template cards were not properly initialised. Now, they are set to `null` unless a template card has a value for them. This needs to be improved later with potential default values (from JSON schema `default`), or from custom field's default values (INTDEV-167). Potentially, also basic types might have default values apart from `null`. But `null` will suffice for now.
When "isms" project is validated with these changes the following validation errors are notified:
When this PR is merged to "main" that …
=> INTDEV-308 Validate 'customFields' in cards

tools/data-handler/src/command-handler.ts
Replace `execSync` with `execSyncFile` and put arguments into an array.
=> Code scanning alert fix: Use arguments array when using 'execSync'

tools/cli/src/index.ts, tools/data-handler/src/command-handler.ts, tools/data-handler/src/create.ts, tools/data-handler/src/index.ts, tools/data-handler/test/command-handler.test.ts, tools/data-handler/test/export.test.ts
Instead of exposing all commands separately, `export` only `command` method and `Cmd` enumeration. 
These together:
- enforce similar interface for all commands
- the new method makes basic validation (project path) for each command (instead of each command separately doing validation for common issues)
This makes most of `CommandHandler` implementation `private`.
Later we can define typings for parameters if we want (ensures that parameters are in correct order).
=> Simplify CommandHandler interface

tools/data-handler/src/create.ts
Code scanner raised an issue about non-complete replacing; i.e. using `replace` without global flag. 
The implementation actually split a long pattern string to parts first, so there were always one `$` and one `^` in each part (at most). But the implementation was ugly (and was noted so in a comment). Replace the implementation with one that uses global flag first, then splits the patterns into strings.
=> Code scanning alert fix: Use global flag when listing type names

tools/data-handler/src/command-handler.ts, tools/data-handler/test/command-handler.test.ts
Currently, it is impossible to create a new project. This is due to that the shared validations for input parameters check that they can find a project folder. 
Creating project should have its own checks. This is different from other commands, which have always 'project' folder to find.
Added also unit test to cover the case.
=> INTDEV-361 Make 'createProject()' use its own sanity checks

tools/data-handler/src/containers/template.ts, tools/data-handler/test/0_validate.test.ts, tools/data-handler/test/command-handler.test.ts
Template creation used wrong path if there were modules imported.
There was a clear programming error, as it was looking for "modules" path to exist, when it should have tried to find "modules/templates/<templateName>"
=> INTDEV-364 Template is created to wrong path

tools/data-handler/src/command-handler.ts, tools/data-handler/src/containers/template.ts, tools/data-handler/src/create.ts
The return type of card creation was changed from `card[]` to `string[]` when `requestStatus` was dropped. 
This causes issues with emitting the changed cards for calculations. 
Switching the return value back to `card[]`.
=> INTDEV-365 Ensure that card array is returned when creating cards

tools/data-handler/src/command-handler.ts, tools/data-handler/test/command-handler.test.ts
There was regression when `CommandHandler` interface was modified: `create project` parameters were flipped in the receiving end.
=> INTDEV-366 'create project' command parameters are in wrong order

tools/data-handler/src/containers/project.ts, tools/data-handler/src/interfaces/project-interfaces.ts
Currently `show module` shows cards, card-types, calculations, templates, workflows and basic info on module.
Field-types are not shown.  Add these to the command output.
=> Show fieldTypes in module details

tools/app/app/cards/[key]/edit/page.tsx
Scroll was not visible because the height of the container was not limited
=> Fix scroll in preview

tools/app/app/components/ContentArea.tsx
h1, h2 and h3 elements were queried sequentially from the html, but now they are queried at the same in order
=> Fix toc order by fetching all elements

tools/cli/bin/run, tools/data-handler/src/command-handler.ts
CLI will now give a human readable message if it is run from a folder which is not the project root or inside of it
=> INTDEV-376 handle errors when using cli

tools/cli/src/index.ts, tools/data-handler/src/command-handler.ts, tools/data-handler/src/export.ts, tools/data-handler/test/export.test.ts
Before, the export command was using flags.  e.g. `cyberismo export -f site …`
After the change, parameters are given as arguments. e.g. `cyberismo export site output`
=> INTDEV-341 use same command format in export command

tools/app/app/api/cards/[key]/a/[attachment]/route.tsx, tools/app/app/api/cards/[key]/a/route.tsx, tools/app/app/cards/[key]/edit/page.tsx, tools/app/app/components/CardContextMenu.tsx, tools/app/app/components/ContentArea.tsx, tools/app/app/components/ContentToolbar.tsx, tools/app/app/components/DnDFile.tsx, tools/app/app/components/modals/AddAttachmentModal.tsx, tools/app/app/components/modals/index.ts, tools/app/app/lib/api/actions/attachments.ts, tools/app/app/lib/api/actions/index.ts, tools/app/app/lib/api/attachments.ts, tools/app/app/lib/api/card.ts, tools/app/app/lib/api/types.ts, tools/app/app/lib/codemirror/index.ts, tools/app/app/lib/definitions.ts, tools/app/app/lib/hooks/redux.ts, tools/app/app/lib/slices/index.ts, tools/app/app/lib/slices/swr.ts, tools/app/app/lib/store.ts, tools/app/app/lib/swr.ts, tools/app/app/lib/utils.ts, tools/app/app/locales/en/translation.json, tools/data-handler/src/containers/card-container.ts, tools/data-handler/src/create.ts, tools/data-handler/src/export.ts, tools/data-handler/src/interfaces/project-interfaces.ts
Attachments can be added, inserted to adoc and deleted.
Attachments are assumed to be either files or images. Images are shown while files can be downloaded.
I also tried server functions in this commit. I think we should continue to use them, if there is no reason not to(=Do we need an external api, I think)
=> Add feature: attachments

package-lock.json, tools/app/__tests__/components.test.tsx, tools/app/app/api/cards/[key]/route.tsx, tools/app/app/cards/[key]/edit/page.tsx, tools/app/app/components/DnDFile.tsx, tools/app/app/components/TreeMenu.tsx, tools/app/app/lib/api/card.ts, tools/app/app/lib/api/types.ts, tools/app/app/lib/definitions.ts, tools/app/app/lib/utils.ts, tools/app/package.json, tools/cli/src/index.ts, tools/data-handler/src/command-handler.ts, tools/data-handler/src/containers/project.ts, tools/data-handler/src/containers/template.ts, tools/data-handler/src/create.ts, tools/data-handler/src/interfaces/project-interfaces.ts, tools/data-handler/src/move.ts, tools/data-handler/src/utils/lexorank.ts, tools/data-handler/test/command-handler.test.ts, tools/data-handler/test/edit.test.ts, tools/data-handler/test/test-data/valid/decision-records/.cards/local/templates/decision/c/decision_1/index.json, tools/data-handler/test/test-data/valid/decision-records/.cards/local/templates/simplepage/c/decision_2/index.json, tools/data-handler/test/test-data/valid/decision-records/.cards/local/templates/simplepage/c/decision_3/c/decision_4/index.json, tools/data-handler/test/test-data/valid/decision-records/.cards/local/templates/simplepage/c/decision_3/index.json, tools/data-handler/test/test-data/valid/decision-records/cardroot/decision_5/c/decision_6/index.json, tools/data-handler/test/test-data/valid/decision-records/cardroot/decision_5/index.json, tools/data-handler/test/utils/lexorank.test.ts, tools/schema/card-base-schema.json
This PR includes ranking for cards:
`cyberismo rank rebalance card` - rebalance children of a specific card. NOTE: this is not recursive
`cyberismo rank rebalance` - rebalance the whole project recursively(also templates)
`cyberismo rank card some_card other_card` - ranks some_card after other_card. It can also be 'first' if you want to rank card as the first card
It should be also mentioned that rebalance-commands work even if the project is missing some or all ranks. Old projects, which do not have ranks, can be updated by running the `cyberismo rank rebalance`-command. Not having project in the card's metadata is not supported
User can drag and drop cards using the tree view. It is possible to move/rank at the same time. When creating a new card, it is added to as the last element.
I …
=> Rank for cards

tools/app/app/cards/[key]/edit/page.tsx
A fixed number was used, now the number of attachments is used
=> Fixed: edit view shows "2 attachments" when there are no attachments

tools/app/app/api/cards/[key]/route.tsx, tools/app/app/lib/api/card.ts, tools/app/app/lib/hooks/redux.ts
Card key is null on the /cards page. createCard-function used to ignore function calls where null was used. Null was replaced with 'root', because the api call is made to `/api/cards/{key}`. It shouldn't be possible to have cards, which have "root" as the key, so there shouldn't be any collisions
=> Allow card creation to root from app

tools/data-handler/src/create.ts
Fixed it by creating a linktypes-directory and a .schema-file in that directory during create-command
=> Fix: Create project fails because of missing linktypes directory

tools/app/app/cards/[key]/edit/page.tsx, tools/app/app/locales/en/translation.json
Preview was shown because edit-page assumed card is always loaded to memory. Now it'll correctly wait for things to load and if they do not load, the page will show an error.
=> fix loading issue with edit page

tools/app/app/cards/[key]/page.tsx, tools/app/app/components/ContentArea.tsx, tools/app/app/lib/api/card.ts, tools/app/app/locales/en/translation.json, tools/data-handler/src/create.ts, tools/data-handler/test/command-handler.test.ts, tools/data-handler/test/test-data/valid/decision-records/.cards/local/linktypes/test-types.json, tools/data-handler/test/test-data/valid/decision-records/.cards/local/linktypes/test.json
Added the following rules:
- Cannot add description if it is not allowed
- Cannot create a link if source is not defined in source card types(empty means any is allowed)
- Cannot creata a link if destination is not defined in destination card types(empty means any is allowed)
On the UI:
- Display only link types, which can be created for the specific card type
- After link type is chosen, only show destinations, which are defined in the configs
- After link type is chose, enable linkDescription box, if link type permits it
Note: Remember to change base branch to main after temp-main has been merged
=> Support for links

tools/app/app/cards/[key]/edit/page.tsx, tools/app/app/lib/api/actions/attachments.ts, tools/app/app/lib/codemirror/index.ts, tools/app/app/locales/en/translation.json, tools/data-handler/src/show.ts, tools/data-handler/src/utils/user-preferences.ts
Adds the following actions:
- Download
- Open in editor
Also, the icons are now hidden by default.
If a command is defined in user preferences, it will try to launch that, otherwise it will use the default app selector of the OS.
It'll wait 1 second for the custom app to start and if it has exited with a non-zero exit code, it will use the default app selector of the OS.
There wasn't a good option for starting an app on windows. Windows seemed to put the app to background. I used a workaround, which starts a cmd prompt and it does work but the user will see a cmd window pop up and destroy itself.
Security:
Custom commands are not escaped in anyway and a shell is used so it is possible to do anything. But it doesn't matter, because these are defined by the user.
Starting the default app is …
=> Attachment actions

tools/app/app/cards/[key]/page.tsx, tools/data-handler/src/calculate.ts
Also fixed a bug: you couldn't make links in which the linkDescription was not enabled
Here's  a generated logic program with links:
% cisms_3
field(cisms_3, "title", "Asset inventory").
field(cisms_3, "cardtype", "page").
field(cisms_3, "workflowState", "Draft").
field(cisms_3, "rank", "0|g").
field(cisms_3, "lastUpdated", "2024-09-03T10:55:37.934Z").
link(cisms_3, cisms_17, "mitigates2", "").
link(cisms_3, cisms_17, "mitigates2", "fdsfsdfdssdfsfs").
link(cisms_3, cisms_17, "mitigates3").
=> Generate links to for logic programming

tools/data-handler/src/calculate.ts, tools/data-handler/src/create.ts
1. Always use function `formatJson()` to write JSON files (makes JSON look similar in all our files).
2. Do not pass default values to fs/promises read/write methods. (interestingly non-promise based fs functions have for example `encoding` null)
=> Always write JSON files through same interface; use defaults

tools/data-handler/src/containers/project.ts, tools/data-handler/test/project.test.ts
Make a check in the update metadata function that if the content is unchanged, do not save the file and update `lastUpdated`.
=> INTDEV-441 If metadata key is unchanged, do not save the JSON file

tools/data-handler/src/validate.ts
Running validation in our "isms" content repo causes perplexing `Cannot read properties of undefined (reading 'length')` error. This is caused by empty `person` data-type in one of the field types. 
To avoid data-type validation to fail, check that the object exists.
=> Empty 'person' fieldtype causes perplexing validation error

tools/app/__tests__/api.test.ts, tools/app/app/api/cardtypes/route.tsx, tools/app/app/lib/api/cardtype.ts, tools/app/app/lib/swr.ts
Fix app cardtype endpoint to support new resource naming scheme.
Pass the cardtype name as url parameter because it typically contains a path.
So the API call is now like:
GET /api/cardtypes?name=cisms/cardtypes/task
Added API test for this.
=> INTDEV-445: Fix to 'Metadata and custom fields do not work in the ISMS project'

tools/app/cypress/e2e/app.cy.ts, tools/data-handler/test/command-handler-rank.test.ts, tools/data-handler/test/command-handler-rename.test.ts
1. `try-catch` in problematic tests test data cleaning. Ignore errors.
2. increase timeout for certain cypress-tests.
3. Put tests that don't need test-data to their own sets and do not fiddle with test data in those (saves some time running tests).
=> Make Windows CI tests more stable

tools/data-handler/src/containers/card-container.ts, tools/data-handler/src/containers/project.ts, tools/data-handler/src/containers/template.ts, tools/data-handler/src/create.ts, tools/data-handler/src/edit.ts, tools/data-handler/src/import.ts, tools/data-handler/src/move.ts, tools/data-handler/src/project-settings.ts, tools/data-handler/src/remove.ts, tools/data-handler/src/rename.ts, tools/data-handler/src/transition.ts, tools/data-handler/src/utils/json.ts, tools/data-handler/src/utils/resource-utils.ts, tools/data-handler/test/project.test.ts
Fix `rename` command after module naming support - INTDEV-420.
Rename now changes all cards and all related resources (card types. workflows, link types, calculations, templates, field types) to new project prefix. Since renaming never affects imported module content, I added to resource fetching from `Project` possibility to fetch just local resources.
Updated cards have their `lastUpdated` timestamps updated.
Additionally, added a check that if project prefix does not change (trying to rename to same prefix), it only complains about that.
Couple changes that are non-essential but I included in this PR:
1) Renamed the `updateMetadata` function from `Project` to `updateMetadataKey` since it only changes only key (and I introduced a new function that updates the whole metadata).
2) …
=> INTDEV-443 Rename does not rename resources

tools/schema/cardsconfig-schema.json, tools/schema/cardtree-directory-schema.json, tools/schema/field-type-schema.json, tools/schema/template-schema.json
Make validation more strict in regards to extra folders and files. 
Generally, no extra files or folders are allowed in project files. Exceptions are
- on root directory, there can be extra files, but no directories
- under each `a` (attachment) directory there can be any files
=> INTDEV-438 Validation: Do not accept extra files or folders in project directory

tools/data-handler/src/calculate.ts, tools/data-handler/src/utils/clingo-parser.ts, tools/data-handler/test/utils/clingo-parser.test.ts
I considered a few options for encoding clingo characters. Since I didn't yet a good idea of characters we could whitelist/blacklist, I ended thinking of encoding/decoding fieldValues for clingo. I considered:
1. Base64
Issue with base64 is that the queries interact with the values and it would be annoying to use base64 for referencing thos e values.
2. Replacing all but certain characters with a formatted string.
I ended up going with this
I put a few things into the whitelist: a-z, A-Z, 0-9 and a few special chars(/, space, |, : and .)
Here's what the generated version looks like:
=> Encode clingo values

tools/schema/cardtree-directory-schema.json
Schema still has old name for the module configuration.
=> Correct configure name for modules

tools/data-handler/src/utils/clingo-parser.ts, tools/data-handler/test/utils/clingo-parser.test.ts
I had one little misunderstanding with the escaping of newlines. This is why our tests were incorrect. Also I noticed that the tests are using the "encodeClingoValue" in them, so most of the parsing tests are successful even if encodeClingoValue / decodeClingoValue are incorrect. I added separate tests for those functions.
Confirmed this works with cyberismo-isms, which contains newlines inside values
=> INTDEV-469 Fixed issue with parsing

tools/data-handler/src/validate.ts, tools/data-handler/test/0_validate.test.ts
Validation complains about resource names if module has been imported.
=> Regression fix: Validation complains about imported module resources

tools/data-handler/src/create.ts, tools/data-handler/src/utils/resource-utils.ts, tools/data-handler/test/utils/resource-utils.test.ts
Fix default link type content when link type is created. As a fix link type will use 'full name' ((project prefix)/linkTypes/(name)).
`cyberismo create linkType test`
`cyberismo show cardType test`
==>
```
{
"name": "project/linkTypes/test",
"outboundDisplayName": "test",
"inboundDisplayName": "test",
"sourceCardTypes": [],
"destinationCardTypes": [],
"enableLinkDescription": false
}
```
Additionally, make function `private` (no need for others to share this).
Rename function from `getLinkTypeContent` to `defaultLinkTypeContent`.
=> INTDE-477 Fix link type default content to use a proper name

tools/data-handler/src/containers/card-container.ts
Change `doCollectAttachments` to collect only from a given folder (and its non-children-card subfolders).
=> INTDEV-487 Collect attachments from one folder only, not from children

tools/data-handler/src/calculate.ts
Remove old folder as first stage of calculations. The subroutines already automatically create folder(s) if they are missing.
=> INTDEV-459 Delete old .calc folder before starting new calculations

tools/data-handler/src/containers/card-container.ts, tools/data-handler/test/show.test.ts
Simplify attachment collecting. Ignore empty 'a' folders.
=> INTDEV-491 Collect attachments correctly even with empty attachment folders

tools/data-handler/src/command-handler.ts, tools/data-handler/src/create.ts, tools/data-handler/test/command-handler-create.test.ts
Allow creation operations to use both long and short names:
`cyberismo create workflow test`
`cyberismo create workflow <prefix>/workflows/test`
Validates that all long name parts match the project prefix and to-be-created resource type.
Drop `local` name part usage from CLI. It is still used internally as a location for local project's resources, but it cannot be referred from CLI commands and shouldn't be visible, other than file paths.
=> INTDEV-475 Allow creation of resource with long and short names

tools/app/app/cards/[key]/page.tsx
`direction` was not included when `createLink` was called.
=> INTDEV-498 Create links with direction (inbound|outbound)

tools/schema/cardTreeDirectorySchema.json
Allow any of the resource directories (either under `.cards/local` or `.cards/modules`) to have `.gitkeep` file in them.
=> INTDEV-503 Allow .gitkeep in resource directories

tools/data-handler/src/containers/template.ts, tools/data-handler/test/command-handler-create.test.ts
`.schema` content was recently changed from object to array of objects.
Template should use the new format when creating cards.
=> INTDEV-502 Create cards with the new .schema format

tools/app/app/components/ContentToolbar.tsx
Decided to hide it, because edit mode only shows links on the preview tab
=> INTDEV-450 Hide link button in edit mode

tools/data-handler/src/calculate.ts, tools/data-handler/src/command-handler.ts
When we run clingo on the command line, we have 3 processes:
* CLI-process
* App-process(child of cli)
* Clingo-processes(child of app)
Since we used the default option when starting the app from cli(stdio="pipe"), the app would crash if it printed too much output into stdout. The cli-process does not care about the app's output, but it might be useful for the user(or not?) so I set  stdio to "inherit", which causes app to write its stdout to cli-process's sdout.
We need the clingo processes stdout so this solution cannot be used there. While the clingo-process was not creating issues now, I also increased its buffer so that we wouldn't get issues with a larger project. I set it to 100MB for now.
=> INTDEV-500 direct app output to parent process stdio

tools/app/app/components/macros/CreateCards.tsx, tools/data-handler/src/create.ts
Changes:
* createCards macro jumps to view mode rather than edit mode
* Template long name was being compared to template short name. Now we use short name for comparisons
=> INTDEV-504 Always jump to view mode and the highest ranked root-level template card

tools/data-handler/src/containers/template.ts, tools/data-handler/test/command-handler-create.test.ts
Now when template is created, also in template's main folder the .schema is written in correct format. 
Note that I needed to turn off link creation tests since adding the new unit test revealed issues with link schema (see INTDEV-512).
=> INTDEV-511 Write .schema file when creating template

tools/app/app/locales/en/translation.json
Consistently - for now - define all translations so that only first word is capitalised. If we want to later have titles with All Words capitalised, let's define separate "...Caption" translation IDs for these cases.
=> Make translations consistently use lower case in non-first words

tools/app/app/api/cards/[key]/a/[attachment]/route.tsx
Browser caches images automatically, but it is now disabled.
=> INTDEV-516 prevent caching attachments

tools/data-handler/src/calculate.ts, tools/data-handler/src/containers/project.ts, tools/data-handler/src/containers/project/project-paths.ts, tools/data-handler/src/containers/template.ts, tools/data-handler/src/create.ts, tools/data-handler/src/edit.ts, tools/data-handler/src/export-site.ts, tools/data-handler/src/export.ts, tools/data-handler/src/import.ts, tools/data-handler/src/interfaces/project-interfaces.ts, tools/data-handler/src/move.ts, tools/data-handler/src/project-settings.ts, tools/data-handler/src/remove.ts, tools/data-handler/src/rename.ts, tools/data-handler/src/show.ts, tools/data-handler/src/transition.ts, tools/data-handler/src/utils/resource-utils.ts, tools/data-handler/test/export.test.ts, tools/data-handler/test/project.test.ts
Split away from original INTDEV-468 PR. 
A new class that handles resource paths for Project class. 
Encapsulates paths and simplifies Project. In the future (after few PRs) will be responsible for providing basic needs in resource creation. The new methods are not yet used.
=> Add separate class to handle paths for Project class

tools/data-handler/src/command-handler.ts, tools/data-handler/src/containers/project.ts, tools/data-handler/src/interfaces/project-interfaces.ts, tools/data-handler/src/remove.ts, tools/data-handler/test/command-handler-remove.test.ts
Add interfaces for `ResourceTypes` and `RemovableResourceTypes` (not all resources can be removed).
Use these instead of `strings` when handling resources.
This is another one of changes split away from INTDEV-468.
=> Use specified types instead strings when working with resources

tools/data-handler/src/calculate.ts, tools/data-handler/src/containers/project.ts, tools/data-handler/src/move.ts, tools/data-handler/src/rename.ts
Get rid of single boolean parameter in the resource collection functions (`Project.calculations()`) and friends).
Single boolean parameters cause confusion when reading the code. 
Additionally, provide means to collect resources from just modules.
Curiously, `calculations()` has different default parameter than the other ones. I didn't change this, as I didn't want to modify the calls that use default values. Maybe something to check a bit later.
BACKGROUND:
A simplified example of why single boolean parameters are bad for reading the code:
```
this.install(false);
```
There is no way of knowing what the parameter does unless you go and check the `install` function itself.
Compare this with: 
```
this.install(Install.skipValidation); 
```
You can immediately see that this call skips …
=> INTDEV-501 Change resource collection functions signature

tools/data-handler/package.json
Using `mocha` with `ts-node` causes experimental warning for importing JSON file.
It is coming from `mocha` or `ts-node`. We don't really care about the warning (it is fine to import JSON file), so just suppress all experimental warnings. We live on the edge. :)
=> INTDEV-526 Suppress experimental warnings

tools/app/app/components/ContentArea.tsx, tools/data-handler/src/create.ts, tools/data-handler/test/command-handler-create.test.ts
createLink throws an error if trying to link to itself. UI doesn't show itself in the dropdown. Since link tests are disabled, I added I comment that states that this behaviour should be tested in DH when INTDEV-512 is done.
=> INTDEV-473 prevent linking to itself

package-lock.json, tools/cli/package.json, tools/data-handler/package.json
First, update to newer “typescript-eslint” version.
Then, ensure that data-handler and CLI have same versions of libraries that they share.
=> INTDEV-524 Remove ESLint compatibility warning

tools/data-handler/src/export-site.ts, tools/data-handler/test/export.test.ts
Add optional `options` to `ExportSite` command. 
There are a lot of options that we could support for `Antora`, but let's for now just support `--silent`. 
This way unit tests can call site exporting with silent (we are not really interested in if it complains about something) and human users get the full output. 
There is no way to provide the `silent` flag with CLI at the moment. If there is a need for it , let's make a ticket.
Unit tests now look clean:
(note that I also renamed the unit test as the original name didn't make any sense)
=> INTDEV-525 Remove stdout/stderr prints from export-site unit tests

tools/app/app/components/TreeMenu.tsx, tools/app/app/components/modals/MoveCardModal.tsx
When you moved the card via move card dialog, user was being redirected to the parent card and treemenu was not updated. Now it stays on the page and updates treemenu.
=> INTDEV-486 fix  move card dialog

tools/data-handler/src/containers/card-container.ts, tools/data-handler/src/containers/template.ts, tools/data-handler/src/create.ts, tools/data-handler/test/template.test.ts
Now parentPath returns "root" also for parents of root template cards. Now it's more easier to know whether a template card is a root card or not
=> INTDEV-508 return root instead of the template name in case of a root template card

tools/data-handler/src/utils/clingo-parser.ts, tools/data-handler/test/utils/clingo-parser.test.ts
Removed condition of clingo parser, which caused empty strings to become undefined. This also happened only if the empty string was the last argument
=> INTDEV-527 Fix clingo parser

tools/cli/src/index.ts, tools/data-handler/src/export-site.ts, tools/data-handler/src/export.ts
- Use same query as in app to generate list of cards to show in site/html/adoc export. This guarantees the same content as in app and enables usage of calculated fields in site export
- Tree query results are translated to Card objects since the export functionality uses that internally
- Show progress in site tree menu
- Show additional metadata in site export content area
=> INTDEV-510: Use Clingo query to generate site/html/adoc export

tools/data-handler/src/containers/template.ts
Noticed this after some serious debugging when doing the "new command handler" (INTDEV-531).
The bug causes `Project` template names turn into to using short name format. Which leads to all sorts of nasty "not found" cases.
Ie. first templates are `[decision/templates/decision, decision/templates/simplePage, devision/templates/empty]`. 
Once 'decision' is instantiated, the templates then are `[decision, decision/templates/simplePage, devision/templates/empty]` and so on.
=> INTDEV-531 do not mutate template name parameter

tools/data-handler/src/command-handler.ts, tools/data-handler/src/containers/project.ts, tools/data-handler/src/containers/template.ts, tools/data-handler/src/create.ts, tools/data-handler/src/rename.ts, tools/data-handler/test/template.test.ts
Remove extra `path` parameter as unnecessary. 
Make `Project` the first parameter, so that the parameter order is similar to `Commands`.
=> INTDEV-533 Simplify Template constructor

tools/app/__tests__/api.test.ts, tools/app/__tests__/components.test.tsx, tools/app/app/components/ContentArea.tsx, tools/app/app/components/MetadataView.tsx, tools/app/app/components/modals/NewCardModal.tsx, tools/app/app/lib/api/types.ts, tools/app/app/lib/definitions.ts, tools/app/app/lib/utils.ts, tools/data-handler/src/calculate.ts, tools/data-handler/src/command-handler.ts, tools/data-handler/src/containers/project.ts, tools/data-handler/src/containers/template.ts, tools/data-handler/src/create-defaults.ts, tools/data-handler/src/create.ts, tools/data-handler/src/export.ts, tools/data-handler/src/interfaces/project-interfaces.ts, tools/data-handler/src/interfaces/resource-interfaces.ts, tools/data-handler/src/show.ts, tools/data-handler/src/transition.ts, tools/data-handler/src/types/queries.ts, tools/data-handler/src/validate.ts, tools/data-handler/test/calculate.test.ts, tools/data-handler/test/command-handler-create.test.ts, tools/data-handler/test/project.test.ts, tools/data-handler/test/template.test.ts, tools/schema/cardTreeDirectorySchema.json, tools/schema/templateSchema.json
Make all resource folders optional in the project.
Additionally, make file-based resources work use same implementation in `create.ts`. Remove resource-specific "exists" functions and provide one generic function. 
Additionally, split the "project interfaces" to two: project related interfaces and resource related interfaces. The latter will be moved to `Resource` class once we get to implement it. 
Finally, renamed the resource interface to be more or less similar; `Template` is an exception for now, as there is `Template` class that is exported.
=> INTDEV-468 Make all resource folders optional

tools/data-handler/src/calculate.ts, tools/data-handler/src/containers/card-container.ts, tools/data-handler/src/containers/project.ts, tools/data-handler/src/containers/template.ts, tools/data-handler/src/create.ts, tools/data-handler/src/export-site.ts, tools/data-handler/src/export.ts, tools/data-handler/src/import.ts, tools/data-handler/src/interfaces/project-interfaces.ts, tools/data-handler/src/interfaces/resource-interfaces.ts, tools/data-handler/src/move.ts, tools/data-handler/src/remove.ts, tools/data-handler/src/rename.ts, tools/data-handler/src/validate.ts, tools/data-handler/test/command-handler-remove.test.ts, tools/data-handler/test/show.test.ts, tools/data-handler/test/template.test.ts, tools/data-handler/test/test-data/invalid/missing-cardTypes-subfolder/.cards/local/.schema, tools/data-handler/test/test-data/invalid/missing-cardTypes-subfolder/.cards/local/cardsConfig.json, tools/data-handler/test/test-data/invalid/missing-cardTypes-subfolder/cardRoot/.schema, tools/data-handler/test/test-data/invalid/missing-cardsconfig.json/.cards/local/workflows/decision.json, tools/data-handler/test/test-data/invalid/missing-templates-subfolder/.cards/local/.schema, tools/data-handler/test/test-data/invalid/missing-templates-subfolder/.cards/local/cardsConfig.json, tools/data-handler/test/test-data/invalid/missing-templates-subfolder/cardroot/.schema, tools/data-handler/test/test-data/invalid/missing-workflows-subfolder/.cards/local/.schema, tools/data-handler/test/test-data/invalid/missing-workflows-subfolder/.cards/local/cardsConfig.json, tools/data-handler/test/test-data/invalid/missing-workflows-subfolder/cardroot/.schema
Mandatory arrays can be empty. 
When reading card or metadata from disk, and array values are missing, adds empty arrays in their place. 
This prevents from making changes to schemas, and to the content repositories.
=> INTDEV-543 Replace optional arrays in interfaces with mandatory ones

tools/data-handler/src/export.ts, tools/data-handler/src/macros/report/index.ts, tools/data-handler/test/test-data/valid/decision-records/cardRoot/decision_5/index.adoc
- Run validateMacros for all content to be exported
- Report macros are shown as is, button macros are hidden
- Add valid macros to test data
- Improve html and adoc export layout
=> INTDEV-509: Support macros in exports

tools/data-handler/src/containers/template.ts, tools/data-handler/test/command-handler-add.test.ts
When new card is added to a template (using `cyberismo add`) , add "rank" for the card.
**Note** that "rank" operation is not handled in this PR, see [INTDEV-545](https://cyberismo.atlassian.net/browse/INTDEV-545), this only affects "add".
Removed the `save()` calls to project configuration when new template cards were generated.
=> INTDEV-465 When template card is added, generate rank for it

tools/data-handler/src/export.ts
This is to silence the "ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time" warning. It will still appear when the export command is used. This is a intermediate fix that should be removed once we find a better way to deal with this.
=> Change static macros import to dynamic to avoid warning

tools/data-handler/src/containers/project.ts, tools/data-handler/src/containers/project/resource-collector.ts, tools/data-handler/src/containers/template.ts, tools/data-handler/src/import.ts, tools/data-handler/src/rename.ts, tools/data-handler/src/validate.ts
Separate resource handling from `Project` to its own class.  
From now on, `Project` is basically a stack of cards (`CardContainer`) and `ResourceCollector` owner. 
This change is not visible to other parts of the sources; the changes to various commands is due to fixing the `cardType` api (INTDEV-548) in this PR as well.
=> INTDEV-557 Separate resource handling to its own class

tools/data-handler/src/rename.ts
When `Rename` emitted that data had been changed, it still used a project path parameter, which was removed when `CommandManager` was added. `Calculate` interpreted the parameter as a card key and it led to unhandled property reference. 
Fixed by removing the parameter from emit.
Additionally, added additional, related fixes:
- uncomment the code line that renames cardType `name` . I don't know why it was commented. It leaves the `name` with previous name unless it is changed. 
- rename also the `optionallyVisibleFields`
=> INTDEV-576 Fix renaming crash

tools/schema/cardBaseSchema.json
Remove unnecessary 'direction' from schema. 
There is no code changes required, as app deduces the direction from how the links are used.
=> Remove 'direction' from schema

tools/data-handler/src/containers/project.ts, tools/data-handler/src/validate.ts
Change the order of operations around:
1. validate
2. make card changes (memory)
3. save
To: 
1. make card changes (memory)
2. validate
3. save
Additionally, tweak the `person` validation a bit. Pass a better validation error message forward.
=> INTDEV-569 Validate card changes correctly

tools/data-handler/src/command-handler.ts
Currently when you start cyberismo app via CLI you get a bunch of Next.js output:
```
jaakko@11latoa unified-sdl % cyberismo app
Running Cyberismo app on http://localhost:3000/
Press Control+C to stop.
> @cyberismocom/app@0.1.0 start
> next start
  ▲ Next.js 15.0.3
  - Local:        http://localhost:3000
✓ Starting...
✓ Ready in 211ms
Opal already loaded. Loading twice can cause troubles, please fix your setup.
Opal already loaded. Loading twice can cause troubles, please fix your setup.
```
I propose we ignore the stdio in this case, user does not need to see these. Result:
```
jaakko@11latoa unified-sdl % cyberismo app
Running Cyberismo app on http://localhost:3000/
Press Control+C to stop.
```
=> INTDEV-599: Ignore stdio while running cyberismo app

tools/data-handler/src/containers/template.ts, tools/data-handler/test/template.test.ts
When a card is created from a template, the template name is first normalised (removes 'local' if used, and checks the name format), then it is checked where the template is from. Unfortunately, name normalisation removes the prefix and type (it only returns the identifier; last part of the name). Thus, if there is a template with same identifier in both the local and import modules, it picks up always the local one. 
As a fix, do not use `normalizeTemplateName` when trying to use template. Instead use `resourceNameParts` utility function and use the data it returns to deduce is it a local or module template. Also pass the full template name to `setTemplatePath` function.
I think the whole normalisation function could be removed, but I didn't include it in this PR. I'll do a separate …
=> INTDEV-604 Fix card creation when same identifier in templates

tools/data-handler/src/containers/project.ts, tools/data-handler/src/containers/template.ts, tools/data-handler/src/create.ts, tools/data-handler/src/interfaces/project-interfaces.ts, tools/data-handler/test/template.test.ts
Make `path` mandatory in `Resource`. 
I also thought about making own extended interface type for `Template` (without path) but it would cause more changes and in some cases the path is already set correctly when template is being constructed.
=> INTDEV-535 Make 'path' mandatory in 'Resource'

tools/cli/src/index.ts, tools/data-handler/src/containers/project/resource-collector.ts, tools/data-handler/src/interfaces/project-interfaces.ts, tools/data-handler/src/remove.ts, tools/data-handler/test/command-handler-import.test.ts, tools/data-handler/test/command-handler-remove.test.ts, tools/schema/cardTreeDirectorySchema.json
Now is is possible to remove all four file based resources (cardType, fieldType, linkType and workflow), and two folder based resources (reports and templates). They mainly share the same code for the removing.
Additionally, fixed some unit tests.
OPEN: Should 'calculations' be removable as well?
There were some issues with remove-unit tests, for me, the project does not seem to be fresh in each test.
Should be investigated in its own ticket.
=> INTDEV-476 Remove all possible resources

tools/data-handler/src/containers/project/resource-collector.ts, tools/data-handler/test/test-data/valid/minimal/.cards/local/linkTypes/.schema
This is regression from resource collector implementation: [https://github.com/CyberismoCom/cyberismo/pull/259](https://github.com/CyberismoCom/cyberismo/pull/259) 
The implementation does not check if a local folder exists before it tries to find files related to it.
There might be other ways to reach the same crash than importing.
As a fix add the folder check.
Also: Removed few empty folders from 'minimal' test project. This causes crash in one test when running without this fix; with the fix, the crash is removed.
=> INTDEV-616 Crash importing modules that don't have all resource folders

tools/data-handler/src/calculate.ts, tools/data-handler/src/containers/project.ts, tools/data-handler/test/project.test.ts
This is not related to any JIRA ticket directly. 
I branched this away from re-ranking template cards ticket (INTDEV-545) as I think it is easier to review new project methods separately.
These are the **new** APIs:
`cardPathParts` returns information from card path. There is no longer need to parse the card paths in random functions. This supports project cards, template cards and module template cards (read: all of them)
`createTemplateObjectFromCard` creates `Template` from given `Card`. If you have `Card` instance, there is no longer need to go through all of the `Templates` from a `Project` to get an `Template` instance based on card id.
Additionally, `findSpecificCard` now also supports `Card` as a parameter. Which might sound strange (why would you find a `Card` if you already have …
=> Add new method to create template object from card

tools/data-handler/src/containers/project.ts, tools/data-handler/src/rename.ts, tools/data-handler/test/command-handler-rename.test.ts, tools/data-handler/test/project.test.ts
Add renaming support to card macros, card xrefs and to report's handlebar files.
Macros are in the card content, and we want to avoid making unnecessary changes to the users content. 
Thus, content is first searched with `{{{...}}}` `RegExp` and then inside each of matches, content is replaced with another `RegExp` (using just `<prefix>/`).
xrefs that link to project cards, are also renamed (e.g. `xref:cisms_70[...]` -> `xref:ismo_70[...]`).
Report renaming now also renames references in the handle bar files.
Card content file is only updated, if there are changes to it. And once for all of the various renaming needs (not once per change).
Additionally, noticed that attachment renaming was at some point probably got broken; content should **not** be validated in-between a renaming …
=> INTDEV-573, INTDEV-575, INTDEV-611 Rename expanded

tools/cli/test/cli.test.ts
BAT tests now successfully check that all resource types are removed.
(I removed the console.log after taking the screenshot)
=> INTDEV-601 Enable tests that check resource removals

tools/cli/bin/run, tools/cli/package.json, tools/cli/src/index.ts
Fix the old name use.
Additionally fetch CLI project details from `package.json` instead of duplicating them in the `index.ts` file.
This normally shows `Experimental warning`, but I decided to suppress all warnings in CLI (we really don't need to show users deprecation, or experimental warnings when running CLI).
Finally, fixed some help texts in the CLI.
=> INTDEV-603 CLI shows wrong name

tools/app/app/lib/hooks/redux.ts
Without the helper text, the unload was not called. It isn't visible on screen
=> INTDEV-608 fix unload event issue

tools/data-handler/src/containers/template.ts
Template sub-directories in a project should have two `.schema` files for each template. 
One in the "main" template folder where `template.json` file is, and another one in the "template root" where the cards are (`"main"/c`). 
`.schema` files are used for dynamic validation of the project sources. 
Using these files, the binary version of `cyberismo` is not dependent on project structure version. We can use whichever binary of `cyberismo` to validate any project (compare it with, if valid project structure would be part of binary; old versions of application couldn't validate upcoming versions, and we would need to keep some sort of history support also in the binary. Yuck.)
The current implementation creates an extra `.schema` file for each card added to the template. 
**As a fix, …
=> INTDEV-589 Do not create unnecessary '.schema' files

tools/data-handler/src/containers/project.ts, tools/data-handler/src/create.ts, tools/data-handler/src/utils/resource-utils.ts, tools/data-handler/test/utils/resource-utils.test.ts
Remove old `identifierFromResourceName` function (it was rather recently renamed from `normaliseTemplateName`).
Replace the old function use with functions; `resourceNameParts` and new function `resourceNameToString`.
The new function `resourceNameToString` glues together resource name parts to a single string. Before doing that it checks if the parts are valid. Valid resource names are: empty string, prefix, type and identifier combination and just identifier.
=> INTDEV-605 replace old function with new

tools/cli/tsconfig.json, tools/data-handler/tsconfig.json
Since we already:
*  have TS 5.2.+ (we are using 5.6.3 at the moment)
* we have nodeJS 20+
* even ESLint supports `es2023` since 8.44; we are using 9.x+
--> We can move to "eslint2023". 
This gets us some convenience APIs that were not available earlier.
Haven't spotted any regression, as of yet.
=> INTDEV-610 Use 'es2023' as 'lib' value

tools/data-handler/src/command-handler.ts
To remove `shell: true`, the parameters need to be passed as an array without string literals.
Also make `cwd` to use directly the value, instead of wrapping it to a string literal.
See more from: https://github.com/CyberismoCom/cyberismo/security/code-scanning/7
Note that copilot provided fix didn't work for us; the  `cyberismo app` (which leads to `npm start`)  would fail.
=> INTDEV-622 Safer way to launch 'cyberismo app'

tools/data-handler/src/containers/project/resource-collector.ts, tools/data-handler/test/command-handler-import.test.ts
Current implementation lists all modules with each loop iteration of for-statement.
Thus, with two modules --> shows 4 modules;
with three modules --> shows 9 modules and so on.
Since all modules can be listed in a single iteration, break the loop after first one.
Uncommented a relevant unit test. Let's see if our better Windows slaves can now handle the new files.
=> INTDEV-615 'show modules' shows duplicates

pnpm-lock.yaml, tools/app/package.json, tools/cli/package.json, tools/data-handler/package.json
To fix a security issue in ESLint dependencies (see https://github.com/CyberismoCom/cyberismo/security/dependabot/9),  update ESLint to 9.1.15+.
Since 9.1.15 has issues with ESLint/Typescript modules, update to 9.1.16.
This requires that ESLint/Typescript modules are also updated.
=> Update ESLint to 9.1.15+

tools/app/app/components/modals/NewCardModal.tsx, tools/app/app/locales/en/translation.json
Small adjustment to current NewCardModal to show only filtered/searched results. 
Default view is currently:
The search box is using autofocus to make the usage a bit more easier. The autofocus returning after it has been cleared did not work automatically, not even when I added inputRefs, most likely since the content is generated after the filter has been cleared. 
Search results are always parsed with .toLowerCase(), like:
This will parse the template names and categories
=> INTDEV-632 - Add template search for create new card popup

tools/app/app/components/macros/ScoreCard.tsx, tools/app/app/components/macros/index.ts, tools/data-handler/src/macros/index.ts, tools/data-handler/src/macros/report/index.ts, tools/data-handler/src/macros/scoreCard/index.ts, tools/data-handler/src/macros/scoreCard/metadata.ts, tools/data-handler/src/utils/schemas.ts, tools/data-handler/test/macros/index.test.ts, tools/schema/scoreCardMacroSchema.json
This is a work-in-progress PR for intermediate review, not ready for merging yet.
Here we introduce a new UI macro: scoreCard, which displays a value with added context.
It can be used in card Asciidoc content as follows:
`{{{ scoreCard '{"title": "SDL control adoption", "value": 30, "unit": "%", "legend": "In progress" }' }}}`
It can also be used inside other macros in project resources, such as the report macro Handlebars template, as follows (.hbs code):
```
{{#each results}}
{{{scoreCard (scoreCardParams "Internal control adoption" this.[base/fieldTypes/progress] "%" )}}}
{{{scoreCard (scoreCardParams "Security issues that require attention" this.[usdl/fieldTypes/issueCount] )}}}
{{/each}}
```
scoreCardParams is a Handlebars helper that creates a JSON string out of the given …
=> INTDEV-559: Scorecard macro

calculations/common/base.lp, calculations/common/queryLanguage.lp, calculations/queries/card.lp, calculations/queries/tree.lp, tools/app/__tests__/api.test.ts, tools/app/__tests__/components.test.tsx, tools/app/__tests__/utils.test.ts, tools/app/app/cards/[key]/page.tsx, tools/app/app/components/FieldEditor.tsx, tools/app/app/components/MetadataView.tsx, tools/app/app/components/TreeMenu.tsx, tools/app/app/lib/utils.ts, tools/data-handler/src/calculate.ts, tools/data-handler/src/export.ts, tools/data-handler/src/types/queries.ts, tools/data-handler/src/utils/clingo-parser.ts, tools/data-handler/test/calculate.test.ts, tools/data-handler/test/utils/clingo-parser.test.ts
Features:
The child results in the query language are generalised: there could be multiple types of child results, with different collection names, yielding different array objects as children of the result.
The data type of fields should be included in the query results. Query language could produce 4-member field terms that include the data type, and a more complex term for enums and lists. QueryParser does not depend on project anymore.
For enum and list data types, the results should be objects that include the value, display value and index of the enum value
When sorting by an enum field, used the index property of the enum value.
When sorting by an list field, used the smallest index property of the list value.
Also changed results->children in tree query and results->fields  and …
=> INTDEV-607 implement new query language features

tools/app/app/cards/[key]/edit/page.tsx
Preview was not visible, because we changed the type of card, but used it still the old way. It was not captured by typescript for some reason.
=> INTDEV-642 fix preview

pnpm-lock.yaml, tools/app/next.config.mjs, tools/app/package.json
Reverts CyberismoCom/cyberismo#367
We can't remove the nextjs config, because DH still uses handlebars and then nextJS fails to resolve it.
=> Revert nextjs config change

tools/cli/bin/run, tools/data-handler/src/interfaces/macros.ts, tools/data-handler/src/macros/BaseMacro.ts, tools/data-handler/src/macros/createCards/index.ts, tools/data-handler/src/macros/index.ts, tools/data-handler/src/macros/report/index.ts, tools/data-handler/src/macros/scoreCard/index.ts, tools/data-handler/src/validate.ts, tools/data-handler/test/macros/index.test.ts
- Introduce a new mode for macro evaluation: validate, which only runs validation for macro content and produces no output.
- Validation mode checks that necessary parameter are available in correct format and throws errors if not. Other modes (inject & static) produce Asciidoc error output in case of errors.
- Use this mode during `cyberismo validate `command to validate macros inside project card contents
- Update macro tests to use validation mode and remove old validateMacros function, which was only used by tests
There is a remaining issue where the following warning is printed to CLI output:
`ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time`
This is probably because of macro JSON schemas that are being loaded with import in code. I …
=> INTDEV-637: Validate macros

tools/app/app/cards/[key]/edit/page.tsx, tools/app/app/components/EditableField.tsx, tools/app/app/components/FieldEditor.tsx, tools/app/app/components/MetadataView.tsx, tools/app/app/locales/en/translation.json, tools/data-handler/src/containers/project.ts, tools/data-handler/src/export.ts, tools/data-handler/src/validate.ts, tools/data-handler/test/command-handler-show.test.ts, tools/data-handler/test/test-data/valid/decision-records/cardRoot/decision_5/index.json
App: can now add/remove/view labels.
Site export: Labels are also visible
Labels are now validated by DH's validate function. Currently they use the same convention as resource names, but that can be changed if needed
=> INTDEV-542 Add labels support to app

tools/data-handler/src/utils/clingo-facts.ts
Logic programs made from fieldstypes generated the index of customFields based on the customFields array rather than alwaysvisibleFields/optionallyvisible-fields. Fixed it by sorting customFields. Now the order is:
1. Order in alwaysVisibleFields
2. Order in optionallyVisiblefields
3. If not found at all, last
=> INTDEV-646 Sort customFields in logic programs

tools/data-handler/src/command-handler.ts
Instead of showing error message: 
`Input validation error: folder name '' is invalid`
show:
`No 'cardRoot' in the current folder`
=> INTDEV-639 Improve error message when 'cardRoot' is missing

tools/data-handler/src/calculate.ts
Renaming project forces calculations to be updated. Unfortunately, one of the sub-calculation functions does not check that the folder actually exists. Fixed by adding a check that if folder does not exist, skip the calculation part.
=> INTDEV-634 Rename in new project crashes

tools/data-handler/src/validate.ts
Add indication from which card the validation error stems from.
Also list the errors on their own rows, instead of joined together with '/'.
=> Improve validation errors from incorrect labels

tools/data-handler/src/validate.ts
Two fixes: 
1) **INTDEV-644** Validation now checks that card's card type's custom fields exist. Thus, if there is a typo in the card type metadata, validation fails.
2) **INTDEV-648** Validation error when card is missing a custom field value is now clearer. Also, if custom field is missing from card, no other errors are shown (previously it would also complain about `undefined` being of wrong type for the field).
Earlier (if we assume that `base/fieldTypes/owner` is missing from card `docs_30`): 
```
Card 'docs_30' is missing custom field 'name' from 'base/fieldTypes/owner'
In card 'docs_30' field 'base/fieldTypes/owner' is defined as 'person', but it is 'undefined' with value of undefined
```
Now: 
```
Card 'docs_30' is missing custom field 'base/fieldTypes/owner'
```
=> INTDEV-644, INTDEV-648 Improve custom field validation

.github/dependabot.yml
To avoid too frequent (and costly) Pull Requests from dependabot - let's move from weekly to monthly updates.
Security notifications are still immediately available when Github Alerts database is updated (and are visible in the "Security" tab).
=> Change dependabot frequency to monthly

.github/workflows/build-and-test-windows.yml, .github/workflows/build-and-test.yml, calculations/common/base.lp, calculations/common/main.lp, calculations/common/pythonFunctions.lp, environment.yml, tools/data-handler/test/calculate.test.ts
Add two first Python functions for logic programs.
`@daysSince(Date)` returns the number of days since `Date`. If `Date` is not a valid ISO date, then `@daysSince` returns 0. This function is useful, for example, when checking whether a review has expired.
`@concatenate(*args)` takes a variable number of arguments and returns a string that concatenates all arguments. The arguments can be numbers, strings or constants (which are a special case of Clingo functions). This function can be used, for example, to create dynamic strings for notifications and policy check failure error messages.
=> Python functions daysSince and concatenate

calculations/test/model.lp, environment.yml, tools/data-handler/src/calculate.ts, tools/data-handler/src/command-handler.ts, tools/data-handler/src/containers/project/project-paths.ts, tools/data-handler/src/macros/common.ts, tools/data-handler/src/macros/graph/index.ts, tools/data-handler/src/macros/graph/metadata.ts, tools/data-handler/src/macros/index.ts, tools/data-handler/src/utils/schemas.ts, tools/data-handler/test/calculate.test.ts, tools/schema/cardTreeDirectorySchema.json, tools/schema/graphMacroBaseSchema.json
1. Data handler processes all macros of the index.adoc of a card and encounters a graph macro
3. Validate the mandatory parameters of the graph macro
4. Validate the parameters of the graph macro against the view-specific parameter schema (if given)
5. Generate the view logic file using Handlebars and the macro parameters
6. Run clingo for the main, model, view files  and check that it was successful, to get a clingraph logic program
7. Run clinggraph on the clingraph logic program. Save the diagrams to a temporary location
8. Replace the spinner or the cached old copy of the diagram with the new version
Note: I changed the our temp directory to be at root of the project in the `.temp`-folder. This means it must be also added to .gitignore of each project. Templates also use …
=> INTDEV-406: Added graph macro

Dockerfile, package.json
Some notes:
- This Dockerfile is not properly optimized
- Image should be based on some smaller image, like Alpine
- Clingo should be built (with python support) in builder container and installed on the final image
- Current image size is 2.69GB, but could be brought down to 1.5GB
This version is just a enabler for the use of container environments and further optimizations will follow
=> Add Dockerfile to enable container image building

calculations/common/pythonFunctions.lp, tools/data-handler/test/calculate.test.ts
Previously, daysSince did not work for datetimes. We also need a function to get today's date for checking whether a due date has passed.
=> Improve Python function daysSince and implement Python function today

tools/data-handler/src/containers/project.ts, tools/data-handler/src/containers/project/project-paths.ts, tools/data-handler/src/containers/project/resource-collector.ts, tools/data-handler/src/create.ts, tools/data-handler/src/interfaces/project-interfaces.ts, tools/data-handler/src/resources/file-resource.ts, tools/data-handler/src/resources/resource-object.ts, tools/data-handler/src/utils/common-utils.ts, tools/data-handler/src/validate.ts, tools/data-handler/test/project.test.ts, tools/data-handler/test/resources.test.ts, tools/data-handler/test/utils/common-utils.test.ts
Optimize & simplify current implementation.
By making the `ResourceFolderType` use plural names of resources, we can skip some mapping and naive pluralisation in the code.
Additionally, remove functions that become unnecessary: `resourceFullName` and `singularType`.
Edit. Note that this is intentionally targeting a feature branch. Once INTDEV-636 has been merged, content repos need to be updated. Then this can be merged.
=> INTDEV-635 Change ResourceFolderType to use plural resource names

tools/schema/cardTreeDirectorySchema.json
Add `calculations` and `reports` to the module part of the schema.
Make all of the resource types to be references, so that we don't need to duplicate them in local resources and module resources parts.
**Note** that this is intentionally targeting a feature branch. Once PRs for INTDEV-636 and INTDEV-635 have been merged, content repos need to be updated. Then this can be merged.
=> INTDEV-594 add all resource types to module schemas

tools/cli/src/index.ts
Ensure that "project path" help is shown in all levels of CLI help.
Additionally, order the commands (and subcommands) alphabetically, as CLI shows them in that order.
=> INTDEV-628 Ensure that project path help is shown in all help topics

package.json, pnpm-lock.yaml, tools/app/package.json, tools/cli/package.json, tools/data-handler/package.json
Move all shared dependencies from specific tool's package.json to workspace's package.json. 
This way the same version of dependency is shared by all of the tools, if necessary. And we limit the number of Pull Requests that dependabot automatically creates.
Also, move "sinon" dependency in data-handler's package.json to be devDepedency instead of production dependency.
Tested that majority of "scripts" still work.
=> Move shared dependencies to root level

tools/data-handler/src/calculate.ts, tools/data-handler/src/transition.ts
App depends on generating all logic programs again anyway(since everything is not updated) so removing generation of logic programs after a transition actually also improves performance. However, if you do a transition via CLI and run a logic program using the CLI, you'll need to generate the files before doing so.
The original issue was that the modules.lp was not being generated although we delete the whole folder before doing calculations. Also for some reason, after removing that issue, the emit still caused another issue: Clingraph run successfully, but produced an empty image. For now, it's simpler to simply rely on generating all logic programs before calculations. We should be able to get rid of that once the calculations are moved to the resource classes.
=> INTDEV-671 Disable card specific logic program generation

tools/data-handler/src/containers/project.ts, tools/data-handler/src/containers/template.ts, tools/data-handler/src/interfaces/project-interfaces.ts, tools/data-handler/src/show.ts, tools/data-handler/test/project.test.ts
Remove 'find' when checking if a created card ID is used. Instead before creating cards, fetch all cards in the project and check if the created cardID is included or not. 
This makes huge difference once there are more than 1000 cards in the project.
Add new API for this that only fetches cardIDs. While at it, rename existing `listAllCards` to `listCards` and replace boolean parameter with an enum. This way we can control where to look for cards.
=> INTDEV-673 - Performance: Make card creation faster

tools/data-handler/src/containers/template.ts
When cards from template are instantiated, workflow's initial state is fetched to card's metadata. 
Unfortunately, the operation fetches the workflow information twice: 
- first, for general access of workflow
- second time, to find initial state of the workflow
Remove the latter, as the code itself can deduce the initial state.
=> INTDEV-681 Fetch workflow data once per instantiated template card

tools/data-handler/src/utils/random.ts
Start using `crypto.randomInt` instead of `Math.random`.
=> INTDEV-679 switch from Math.random to crypto.randomInt

calculations/queries/card.lp, tools/app/app/cards/[key]/edit/page.tsx, tools/app/app/components/MetadataView.tsx, tools/data-handler/src/containers/project.ts, tools/data-handler/src/containers/template.ts, tools/data-handler/src/interfaces/resource-interfaces.ts, tools/data-handler/src/types/queries.ts, tools/data-handler/src/utils/clingo-facts.ts, tools/data-handler/src/validate.ts, tools/schema/cardTypeSchema.json
This will rename isEditable to isCalculated and prevent saving those. This will still work with repos that use `isEditable`, but I'll make another PR that will remove the backwards compatibility.
=> INTDEV-620 Rename isEditable to isCalculated

tools/app/app/globals.css
Tall graphs look bad with the dataflow module. This change would limit their height to 75% of the viewport height, which seems to yield acceptable results with graph macro but also with other image attachments.
=> Change image max-height to 75vh to make tall graphs render better

tools/data-handler/src/calculate.ts
Remove references to install clingo via "normal means" and instead, reference the installation documentation.
=> INTDEV-655 Re-phrase the error message when clingo is missing

tools/data-handler/src/create.ts
Show the error message from the failed `Promise` instead of `Promise not filled`.
=> INTDEV-676 Show the actual error from Promise

tools/data-handler/src/export-site.ts
Windows environment does not recognize npx command without parameter shell: true. It will cause an error that is handled like successful run, so it never goes to catch block.
=> INTDEV-717 Fix site export on windows

.github/workflows/build-clingo-binaries.yml, .gitignore, LICENSE, package.json, scripts/install-clingo.mjs, tools/cli/bin/run
Postinstall script that will:
- Download our own built clingo from https://github.com/CyberismoCom/cyberismo-base/tags (not public)
- Extract it under vendor/utils
- Download latest graphviz binary
- Extract it under vendor/utils
Run alteration:
- Added custom path for these two binaries, so that runtime inclusion works properly
=> INTDEV-706 Add clingo and graphviz binary postinstall & custom path during execution

tools/schema/cardTreeDirectorySchema.json
Currently, report schema allows that any file can be in the report's folder. 
Make it more strict - only allow listed files. 
Additionally, there is a typo in the schema file. Fix the typo.
=> Fix: schema file name incorrect + do not allow extra files

tools/data-handler/src/resources/file-resource.ts, tools/data-handler/test/command-handler-update.test.ts
Expand identifier-only resource name correctly in resource implementation.
When user did `cyberismo update <resource> change name <identifier-only-name>` the 
`<identifier-only-name>` was stored to resource metadata file. 
The implementation did correctly validate and expand the name, but didn't set it to resource `name`. Thus only `identifier` was stored to metadata file. Which led to resource being impossible to find.
=> INTDEV-682 Resource name update: expand identifier-only correctly

tools/cli/test/cli.test.ts, tools/data-handler/src/create.ts, tools/data-handler/test/command-handler-add.test.ts
When adding cards to a template, it doesn't check that the template actually exists, if its identifier matches and other template's identifier that exists in the project. :)
Unfortunately the tests - both BAT and unit tests - related to the feature were both broken in their own ways.
Add the check - use the whole name, not just identifier. 
Fix also the tests.
=> Add check that template exists when adding cards to it

tools/data-handler/src/create.ts, tools/data-handler/src/validate.ts, tools/data-handler/test/0_validate.test.ts, tools/data-handler/test/command-handler-create.test.ts
Provide separate functions for validating labels and project names. Previously they were validated as resource names (read: identifiers). 
Labels now accept almost anything. They cannot start with whitespace and can then contain alphanumerical characters plus whitespace and '.', '_', '-'. 
Project names follow similar rules to identifiers, but should be at most 64 characters. This to avoid issues with some Windows configurations when path and filename is longer than 256 characters. The OS can be configured so that path can be 32k+characters, but we can't trust that every user would have it set up. The individual file name (sans path) can be 256 characters in Windows. 
Finally, renamed `isValidResourceName` to `isValidIdentifier` as it was actually just checking the identifier part of a …
=> INTDEV-629 Separate functions to validate labels and project names

tools/app/app/components/ContentArea.tsx, tools/app/app/components/macros/CreateCards.tsx, tools/app/app/components/macros/index.ts, tools/data-handler/src/macros/index.ts, tools/data-handler/test/macros/index.test.ts
Using constructor in react directly is bad practice so started using createElement itself. Also created a unique key for each macro, which is done on server side, since it's much easier to do so.
Issue: Without the given changes, React crashed because the current component detected that the amount of used hooks changed. This is because the macros were not tracked separately by React. This fix should also fix a lot of other bugs that might have resulted from using constructor directly without a unique key.
=> INTDEV-709 use createElement instead of constructor directly

tools/app/app/globals.css
We had unused space on larger screen because of max-width. For now I removed it
=> INTDEV-654 remove max width from content in contentarea

tools/data-handler/src/containers/project.ts, tools/data-handler/src/containers/template.ts
Previously, when template cards were created, they were first created to a `.cards/temp` folder. Then if card creation succeeded, cards were copied to correct place and temp data was deleted. 
To make template card instantiation simpler, create cards directly to correct place. If there is an error instantiating the cards, use the mapping table to remove the partially created template cards.
=> INTDEV-692 Optimize template card instantiation

pnpm-lock.yaml, tools/app/__tests__/components.test.tsx, tools/app/app/components/TreeMenu.tsx, tools/app/app/lib/hooks/utils.ts, tools/app/package.json
We took the reference for use-resize-observer from the wrong object so I fixed it. Also removed the use-resize-observer dependency, because it was fairly easy to do for our case and the module does not support React 19 #138
=> INTDEV-670 Remove use-resize-observer and fix scroll bug

tools/data-handler/src/macros/report/index.ts, tools/data-handler/src/resources/file-resource.ts, tools/data-handler/test/resources.test.ts
Report resource is required to have its "auxiliary" data (schema et al) when it is instantiated within macros.
Second; the inner paths of module resources were set incorrectly; they always pointed to local resource folders.
Added also unit test that imported `report` can be shown and there are no errors.
=> Fix: Fetch report data correctly for macros

tools/data-handler/src/containers/template.ts, tools/data-handler/src/resources/create-defaults.ts, tools/data-handler/test/command-handler-create.test.ts
When cards are added, set all non-calculated custom fields to 'null'.
I created a default card content function to `DefaultContent` static class. This cleans up `Template` class implementation. Also moved some related internal functions there. 
I also added tests for using the new default content.
=> INTDEV-686 Add cards to template: set custom fields to null

pnpm-lock.yaml, tools/app/package.json
There are two issues related to `codeMirror`. 
Quite often the library updates when another library is updated. E.g. `pnpm update mocha`
Not all of the combinations of sub-dependency versions of codeMirror work internally together. 
To avoid both issues, let's freeze the codeMirror versions to certain specific version and define all of the codeMirror sub-dependencies as `peerDependencies` to avoid them being changed. I have frozen the versions to a specific set of versions that seemingly work together.
=> INTDEV-739 Ensure that @codemirror library versions are locked

tools/app/app/components/TreeMenu.tsx, tools/app/app/lib/hooks/utils.ts, tools/app/cypress/e2e/app.cy.ts
Looks like the issue was actually not in the resizeobserver. At the same time we also changed the treeview so that it contains two use-resize-observer calls and setting height to 0 seemed to cause issues. Fixed it by setting height to undefined if it is not yet available.
Tested with Chrome and Firefox
=> Fix disappearing tree

tools/data-handler/src/resources/card-type-resource.ts, tools/data-handler/src/resources/field-type-resource.ts, tools/data-handler/src/resources/file-resource.ts, tools/data-handler/src/resources/link-type-resource.ts, tools/data-handler/src/resources/report-resource.ts, tools/data-handler/src/resources/template-resource.ts, tools/data-handler/src/resources/workflow-resource.ts
Renaming a project causes all resources to rename themselves. 
The faulty implementation wrote JSON file in the middle of operation and then wrote it again at the end of the operation. 
Since file operations are done with threads in nodeJS, this caused a race-condition in which the other write yielded some garbage to the file. 
Fixed by removing the "middle" write. Resource JSON is written after all operations related to renaming have been finished.
=> INTDEV-751 Rename writes garbage to card type JSON files

tools/data-handler/src/command-handler.ts
Values 'format' and 'output' are no longer used, so remove them.
=> INTDEV-649 Remove outdated CardOptions values

tools/data-handler/src/containers/card-container.ts, tools/data-handler/src/resources/card-type-resource.ts, tools/data-handler/src/resources/field-type-resource.ts, tools/data-handler/src/resources/file-resource.ts, tools/data-handler/src/resources/folder-resource.ts, tools/data-handler/src/resources/link-type-resource.ts, tools/data-handler/src/resources/report-resource.ts, tools/data-handler/src/resources/resource-object.ts, tools/data-handler/src/resources/template-resource.ts, tools/data-handler/src/resources/workflow-resource.ts, tools/data-handler/src/utils/card-utils.ts, tools/data-handler/test/command-handler-remove.test.ts, tools/data-handler/test/resources.test.ts, tools/data-handler/test/utils/card-utils.test.ts
Add new API `usage` to resources. This returns an array of references (card keys, resource names, or calculation file names) where the resource is used. Array is always returned so that card key references are first, then resource names and finally calculation filenames. Cards are sorted first by project prefix, then by card ID. Duplicates are removed by using a `Set`. This is not performance critical for now, thus using `Array` -> `Set` -> `Array` is fine. If it is seen as a problem, `Set` can be replaced with a `filter -> includes-indexOf` call, though it can be slower.
For future consideration. The references could be returned in subarrays (`card-references: [...], resource-references: [...], calculation-references: [...]`), if we need to use the references for anything. For now it is …
=> INTDEV-578 Do not allow 'remove' when resource is in use

tools/cli/src/index.ts, tools/cli/src/resource-type-parser.ts, tools/data-handler/src/command-handler.ts, tools/data-handler/src/create.ts, tools/data-handler/src/index.ts, tools/data-handler/src/macros/report/index.ts, tools/data-handler/src/remove.ts, tools/data-handler/src/resources/card-type-resource.ts, tools/data-handler/src/show.ts, tools/data-handler/src/utils/resource-utils.ts, tools/data-handler/test/command-handler-show.test.ts, tools/data-handler/test/show.test.ts, tools/data-handler/test/utils/resource-utils.test.ts
Allow commands 'create', 'remove' and 'show' to be used also with resource names (<prefix>/<type>/<identifier>) without proving the type separately.
Earlier user needed to define the type with resources and as resource name contains type, it seems a bit redundant:
`
cyberismo show linkType ismsa/linkTypes/mitigates
`
Now, if user wants to skip the type, it is possible
`
cyberismo show ismsa/linkTypes/mitigates
`
The previous way is still supported.
There is quite a lot of code for such a simple change. This is due to that `Commander` does not really support "dynamic" commands (ie. argument can be different thing depending on context), it is all about defining the command before hand.
A lot of changes in other than CLI / `CommandHandler` files are due to better validation and checks. If it …
=> INTDEV-478 CLI: Make create/remove/show/ commands use resource name directly

calculations/common/pythonFunctions.lp, tools/data-handler/test/calculate.test.ts
Graphviz or clingraph do not wrap texts automatically, so we could do this with a python function. I tested this successfully also with some graphs.
=> INTDEV-769 Add a new python function wrap

tools/data-handler/src/containers/template.ts, tools/data-handler/src/import.ts
Creating a new instance of `Project` is quite expensive operation and it should not be taken lightly. 
Removing two unnecessary calls to create a `Project` instance:
- from `Import` - the source project is always the one that `Import` class is having as a property
- from `Template` - the `project` parameter is no longer optional parameter - has not been for some time, so it shouldn't create a project ever
=> Remove two unnecessary 'new Project' calls

calculations/common/base.lp, calculations/queries/tree.lp, tools/app/app/components/TreeMenu.tsx, tools/data-handler/src/export.ts, tools/data-handler/src/types/queries.ts
For now, there is a compatibility rule in place as well.
I tested that both the old and the new styles of enabling progress metrics work.
=> Rename base/fieldTypes/progress as progress

tools/data-handler/src/containers/template.ts, tools/data-handler/src/validate.ts, tools/data-handler/test/command-handler-create.test.ts, tools/data-handler/test/test-data/invalid/invalid-card-has-wrong-state/.cards/local/cardtypes/decision.json, tools/data-handler/test/test-data/invalid/invalid-card-has-wrong-state/.cards/local/cardtypes/decisionWrongWF.json, tools/data-handler/test/test-data/invalid/invalid-card-has-wrong-state/.cards/local/templates/decision/c/decision_1/index.json, tools/data-handler/test/test-data/invalid/invalid-card-has-wrong-state/cardRoot/decision_5/c/decision_6/index.json, tools/data-handler/test/test-data/invalid/invalid-card-has-wrong-state/cardRoot/decision_5/index.json, tools/data-handler/test/test-data/invalid/invalid-card-has-wrong-state/cardRoot/decision_7/index.json, tools/data-handler/test/test-data/invalid/invalid-card-has-wrong-state/cardRoot/decision_8/index.json, tools/data-handler/test/test-data/invalid/invalid-cardsconfig.json/.cards/local/cardtypes/decision.json, tools/data-handler/test/test-data/invalid/invalid-cardsconfig.json/.cards/local/templates/decision/c/decision_1/index.json, tools/data-handler/test/test-data/invalid/invalid-wrong-resource-names/.cards/local/templates/decision/c/decision_1/index.json, tools/data-handler/test/test-data/invalid/missing-cardsconfig.json/.cards/local/templates/decision/c/decision_1/index.json, tools/data-handler/test/test-data/valid/decision-records/.cards/local/cardTypes/decision.json, tools/data-handler/test/test-data/valid/decision-records/.cards/local/templates/decision/c/decision_1/index.json, tools/data-handler/test/test-data/valid/decision-records/cardRoot/decision_5/c/decision_6/index.json
When instantiating cards from template to JSON files, the calculated fields can just be skipped. 
Additionally, add to tests a calculated field ("obsoletedBy"). Change test assets accordingly and add a check to one of the tests that ensures that calculated field value is not copied to JSON file.
=> INTDEV-777 Filter out calculated fields when instantiating cards

tools/data-handler/src/command-manager.ts, tools/data-handler/src/containers/card-container.ts, tools/data-handler/src/containers/project.ts, tools/data-handler/src/transition.ts
Previously, `findCard` tried to look for - recursively - all the subfolders of a project. Including `.git` and `.calc`. 
This caused some issues when `.calc` folder content was deleted while recursion was ongoing (transition caused calculation files to be deleted as part of new calculations). 
As a fix; only look certain subfolders when updating the card. Project cards from `cardRoot` and template cards from `.card/local/templates`. Module cards are never updated. 
Additional two optimisations: 
1) Do not call `readdir` if already having found the card.
2) Do not write `lastTransitioned` through Edit command, but directly after transition, if it succeeds.
=> INTDEV-774 Look for card from appropriate places only

tools/data-handler/src/transition.ts
There was a recent fix to transitions (INTDEV-774). 
The fix to that exposed a problem in current transition operation that surfaces sporadically:
- write metadata for state change
- this will cause calculations to be updated
- meanwhile, another write to same metadata is issued to update the timestamps
Sometimes either the READ op (for calculations) or WRITE op (for timestamps) will fail. 
This is probably due to racing condition trying to access the same file.
As a fix, write all changes to the metadata (state & timestamps) in one operation.
=> INTDEV-778 Transition: Write all changes to metadata in one operation

calculations/queries/tree.lp, tools/app/__tests__/api.test.ts, tools/app/app/components/TreeMenu.tsx, tools/app/app/lib/utils.ts, tools/data-handler/src/interfaces/resource-interfaces.ts, tools/data-handler/src/types/queries.ts, tools/data-handler/test/calculate.test.ts, tools/schema/workflowSchema.json
Added the statusIndicator and removed workflowStateCategory. It still exists for each card still, but it is currently not used anywhere. Confirmed the given logic works with cyberismo-isms(swap cardtype with cardType)
=> INTDEV-454 Add statusIndicator

tools/data-handler/src/validate.ts, tools/data-handler/test/0_validate.test.ts, tools/data-handler/test/command-handler-create.test.ts, tools/data-handler/test/command-handler-update.test.ts, tools/data-handler/test/resources.test.ts, tools/schema/cardTreeDirectorySchema.json, tools/schema/cardTypeSchema.json, tools/schema/reportSchema.json, tools/schema/templateSchema.json, tools/schema/workflowSchema.json
Allow resource identifiers (last part of "name") to consists of numbers; or contain numbers.
=> INTDEV-656 Allow resource identifiers to contain numbers

tools/data-handler/src/resources/folder-resource.ts, tools/data-handler/src/resources/template-resource.ts
Folder-resource's internal folder doesn't change when resource `name` is changed. The metadata JSON file is correctly renamed.
The problem affects all of the folder-based resources (templates and reports; and incoming graphViews and graphModels).
=> INTDEV-793 Rename internal folder when resource 'name' changes

calculations/queries/onCreation.lp, calculations/queries/onTransition.lp, tools/data-handler/src/calculate.ts, tools/data-handler/src/card-metadata-updater.ts, tools/data-handler/src/resources/field-type-resource.ts, tools/data-handler/src/transition.ts, tools/data-handler/src/types/queries.ts, tools/data-handler/test/calculate.test.ts, tools/data-handler/test/command-handler-rank.test.ts, tools/data-handler/test/command-handler-remove.test.ts, tools/data-handler/test/field-type-from-clingo.test.ts
Two new internal queries added: 
1) `onTransition` which is executed when state change for a card occurs. 
2) `onCreation` which is executed when cards are created. 
These queries return both "updateFields" array that define fields that need to be changed.
**LIMITATIONS**
Currently, `cardType` and `rank` cannot be changed through queries.
The first since it would basically require the card to be re-written and all new values provided; easier to just delete and then create a new card with a new type. 
The second since I doubt that users can provide valid rank as lexorank value. 
Noticed during implementation of this feature that "static" card metadata could also be fieldtypes which would in some cases make the implementation here and there a bit simpler. Ticket: …
=> INTDEV-712 Support for applying changes when card state changes

tools/data-handler/src/containers/template.ts, tools/data-handler/src/interfaces/project-interfaces.ts, tools/data-handler/test/template.test.ts, tools/schema/cardBaseSchema.json
When card is instantiated, store the template card key to `templateCardKey` property of metadata.
This needs to be done in reverse-lookup (convert Map to array; use `find()` , but since this is a small map and requires no file operations, it is fast enough) to get the value from `Map`.
=> INTDEV-127 Card instantiation: store template card key to card metadata

tools/app/app/api/fieldTypes/route.tsx, tools/app/app/api/linkTypes/route.tsx, tools/cli/src/index.ts, tools/cli/src/resource-type-parser.ts, tools/data-handler/src/command-handler.ts, tools/data-handler/src/containers/project.ts, tools/data-handler/src/containers/project/project-paths.ts, tools/data-handler/src/containers/project/resource-collector.ts, tools/data-handler/src/create.ts, tools/data-handler/src/interfaces/project-interfaces.ts, tools/data-handler/src/interfaces/resource-interfaces.ts, tools/data-handler/src/remove.ts, tools/data-handler/src/rename.ts, tools/data-handler/src/resources/create-defaults.ts, tools/data-handler/src/resources/graph-model-resource.ts, tools/data-handler/src/resources/graph-view-resource.ts, tools/data-handler/src/resources/report-resource.ts, tools/data-handler/src/show.ts, tools/data-handler/test/resources.test.ts, tools/data-handler/test/show.test.ts, tools/data-handler/test/test-data/valid/decision-records/.cards/local/graphModels/.schema, tools/data-handler/test/test-data/valid/decision-records/.cards/local/graphModels/test.json, tools/data-handler/test/test-data/valid/decision-records/.cards/local/graphViews/.schema, tools/data-handler/test/test-data/valid/decision-records/.cards/local/graphViews/test.json, tools/data-handler/test/test-data/valid/decision-records/.cards/local/graphViews/test/view.lp.hbs, tools/schema/graphMacroBaseSchema.json, tools/schema/graphModelSchema.json, tools/schema/graphViewSchema.json
Add two new resource types: graph models and graph views.
New resources support all available commands and functionalities (no calculations for them are being generate at the moment though).
Removed resource-specific `show` functions from `show` command; and instead use a generic `showResource()` instead.
**Migrator**
Unzip the package.
In the unzipped directory, execute `node migrator.js <path to the root of a project>`
The tool automatically converts existing graph models and graph views to have proper configuration files and the resource folder to have correct `.schema` file in place. After migration, please check that the migration worked correctly by running validation.  Do not migrate content repos until this PR has been merged. …
=> INTDEV-772 Add resource types 'graphModels' and 'graphViews'

tools/data-handler/src/commands/create.ts, tools/data-handler/src/commands/remove.ts, tools/data-handler/src/commands/rename.ts, tools/data-handler/src/commands/transition.ts
Four commands affected. For some reason in INTDEV-671 the `emit` was already removed from `Transition` command, but the `EventEmitter` inheritance was left as-is. 
I also changed the Copyright blocks to NOT have 80+ characters per row for the changed sources.
=> INTDEV-795 Remove EventEmitters and call 'Calculate' directly

tools/data-handler/src/containers/card-container.ts, tools/data-handler/src/containers/project.ts, tools/data-handler/src/containers/template.ts
Three small optimisations for finding cards: 
1) If result is impossible, return `undefined`. Impossible results are finding a module template card from project cards; or finding a project card from module template cards. 
2) Find cards from templates parallel instead of sequential. Consumes more memory, but should be generally faster.
3) Remove unnecessary `Regex` test when trying to find a card. There is no need to check if the searched cardKey complies with `Regex` pattern.
All in all, on my Mac these make showing a card from CLI ~10% faster. Can have more impact on slower machines.
=> INTDEV-775 Optimize find card functions

tools/cli/src/index.ts, tools/data-handler/src/commands/update.ts, tools/data-handler/src/resources/array-handler.ts, tools/data-handler/src/resources/card-type-resource.ts, tools/data-handler/src/resources/field-type-resource.ts, tools/data-handler/src/resources/resource-object.ts, tools/schema/resources/fieldTypeSchema.json
Allow field type with `enum` data type to be updated with `update` command. 
All operations (`add`, `change` or `remove`) are supported.
The operations need to be mostly implemented as exceptions in `FieldTypeResource` class since `enum` values do not have the generic object structure that other resources have (If they'd be `{"name": <value of enum>, "displayName": <display name>, "description": <description>}` this would be somewhat simpler change.
Alternatively, we could handle the "special case of ''enumValue" in the `ArrayHandler`.
There was a bug in the `ArrayHandler` class. The search for existing value ended up comparing `undefined` to `undefined` when trying to find `name` from the object. Therefore it assumed - incorrectly - that value already existed.
I also added support for …
=> INTDEV-580 Allow 'enum' value to be updated

pnpm-lock.yaml, tools/cli/package.json, tools/cli/src/index.ts, tools/data-handler/src/command-handler.ts
Run validation before starting the app.
Use `inquirer` module's `confirm` implementation to ask a question from user when he/she is trying to start app and there are validation errors. 
If user presses `n` (or other false value) and presses Enter, then `cards app` is stopped. 
If user presses `Y` (or any other truth value) and presses Enter,  then `cards app` will start the application.
Validation errors are shown as a list; each on its own row. If there are more validation errors than a limit (hard coded 10; can be changed to some other if wanted); then only first N errors are shown, then "..." and rest of the messages are removed. This is to ensure that user still remembers the context. 
If user does not answer to the confirmation, `Y` is automatically assumed, after 10 seconds.
If user …
=> INTDEV-760 Validate project before staring app

tools/data-handler/src/macros/index.ts, tools/data-handler/test/macros/index.test.ts
Seems that using block passthrough (q.v. https://docs.asciidoctor.org/asciidoc/latest/pass/pass-block/) inside a table leaves extra plusses on either side of macro. 
Switch to using inline passthrough (q.v. https://docs.asciidoctor.org/asciidoc/latest/pass/pass-macro/); they seem to work both outside and inside of a table.
=> INTDEV-814 Use inline passthrough instead of block to avoid extra '+'s

tools/data-handler/src/commands/calculate.ts, tools/data-handler/src/commands/remove.ts, tools/data-handler/src/containers/project.ts, tools/data-handler/test/project.test.ts
Fetch the needed details already in `Remove` (it is already fetching card details, so it could fetch ones that `Calculate` can use). Then use the card with received details in `Calculate`. Remove the extra fetch. It was only place where `Card` was used as a parameter for `findSpecificCard` and that API has broken at some point. Remove the `Card` parameter type support from `findSpecificCard` - use only card key string from now on.
=> INTDEV-805 Retrieve affected cards correctly in Calculate

tools/data-handler/src/commands/calculate.ts, tools/data-handler/test/command-handler-remove.test.ts, tools/data-handler/test/remove.test.ts
When a card is deleted, the card and its children should be removed from `cardTree.lp`. 
That way there is no need to update the calculations when deletion occurs. 
The existing implementation assumed that cards have relative path, when they nowadays have absolute path. Therefore, the file remained unmodified. Fixed, by using only a partial name when updating the file.
=> INTDEV-806 Update 'cardtree.lp' correctly when card is deleted

tools/data-handler/src/containers/project.ts, tools/data-handler/src/utils/card-utils.ts, tools/data-handler/test/utils/card-utils.test.ts
Instead of function level recursion, use `readdir` with `recursive: true`.
First, builds up a card map for the cards, then fetches metadata for each card and finally builds the hierarchy. 
This takes roughly 70% of the time that the previous implementation took on my Mac. App calls this once per change (status change, or edit metadata), so the gains are cumulative.  
Noted while checking the performance that nodeJS (or Mac file system?) caches `readdir` results. If you need to make a performance improvement, call the `readdir` function once before measurements with the path you are using. That way you can compare different implementations side-by-side.
=> INTDEV-811 Optimize showProjectCards function

package.json
Dependabot uses v20 so let's allow it. Unfortunately, this means that if user runs with v20, it is allowed.
=> INTDEV-822 allow v20

tools/app/src/components/ContentArea.tsx, tools/app/src/components/ContentToolbar.tsx, tools/app/src/components/StateSelector.tsx, tools/app/src/components/macros/CreateCards.tsx, tools/app/src/components/modals/AddAttachmentModal.tsx, tools/app/src/components/modals/DeleteModal.tsx, tools/app/src/components/modals/EditLinkModal.tsx, tools/app/src/components/modals/MoveCardModal.tsx, tools/app/src/components/modals/NewCardModal.tsx, tools/app/src/lib/api/action-types.ts, tools/app/src/lib/api/attachments.ts, tools/app/src/lib/api/card.ts, tools/app/src/lib/api/types.ts, tools/app/src/lib/hooks/redux.ts
Spinners are specific to actions, while updates disable buttons of similar kind globally
=> Add action specific spinners

tools/data-handler/src/macros/index.ts
Code scanning tools complain about this regex that it might cause performance issues on some content. 
Replace the regex with non-greedy one.
See details from: https://github.com/CyberismoCom/cyberismo/security/code-scanning/37
=> SECURITY FIX: Use non-greedy regex

tools/data-handler/src/commands/export-site.ts, tools/data-handler/src/commands/export.ts
There was a bug in the export implementations where whole card tree was always returned when a partial card tree was requested.
As a fix, instead of processing the whole card tree result set, find the required card from the results, and then process only that sub-tree.
=> INTDEV-812 Allow exporting partial cardtree

tools/data-handler/src/command-handler.ts, tools/data-handler/src/commands/create.ts, tools/data-handler/src/commands/validate.ts, tools/data-handler/src/interfaces/project-interfaces.ts, tools/data-handler/src/interfaces/resource-interfaces.ts, tools/data-handler/src/resources/field-type-resource.ts, tools/data-handler/src/resources/file-resource.ts, tools/data-handler/src/utils/common-utils.ts, tools/data-handler/src/utils/value-utils.ts, tools/data-handler/test/resources.test.ts, tools/data-handler/test/test-data/valid/decision-records/.cards/local/fieldTypes/numberOfCommits.json, tools/data-handler/test/test-data/valid/decision-records/cardRoot/decision_5/c/decision_6/index.json, tools/data-handler/test/utils/value-utils.test.ts
From now on, it will be possible to change the data type of a field type through `update` command. 
The operation automatically changes all cards that use field type (through the card type), if it can. 
If the data type can be changed, but some of the card data cannot (for example to change field "email" from string to "person", but some card has invalid email address), the resource is changed and all value change operations that failed are logged (=shown to CLI user).
I included also possibility to use `BigInt` values, if `string` types have some gigantic number value in them. 
If reviewers think this is too much, I can omit it from this change. Remember that JS number values are actually only 52-bit floats/integers. Thus they are not compatible in the upper/lower range with let's say …
=> INTDEV-799 Change type of data in field type

tools/backend/src/routes/cards.ts, tools/data-handler/src/command-handler.ts, tools/data-handler/src/commands/calculate.ts, tools/data-handler/src/commands/create.ts, tools/data-handler/src/commands/export.ts, tools/data-handler/src/commands/validate.ts, tools/data-handler/src/containers/card-container.ts, tools/data-handler/src/containers/project.ts, tools/data-handler/src/containers/project/resource-collector.ts, tools/data-handler/src/containers/template.ts, tools/data-handler/src/macros/graph/index.ts, tools/data-handler/src/project-settings.ts, tools/data-handler/src/resources/file-resource.ts, tools/data-handler/src/resources/graph-model-resource.ts, tools/data-handler/src/resources/graph-view-resource.ts, tools/data-handler/src/resources/report-resource.ts, tools/data-handler/src/resources/template-resource.ts, tools/data-handler/src/utils/common-utils.ts, tools/data-handler/src/utils/file-utils.ts, tools/data-handler/src/utils/json.ts, tools/data-handler/src/utils/value-utils.ts, tools/data-handler/test/command-handler-create.test.ts, tools/data-handler/test/command-handler-import.test.ts, tools/data-handler/test/command-handler-transition.test.ts, tools/data-handler/test/command-handler-validate.test.ts, tools/data-handler/test/project.test.ts, tools/data-handler/test/show.test.ts, tools/data-handler/test/utils/file-utils.test.ts
Remove as many of the `pathExists` calls as possible. 
Generally, it is a bad code to first check if something exists and then try to read it. Instead just try to read the file / dir and handle the error / exception if any. This way we can avoid problematic timing issues when:
- check if file exists before an asynchronous read call... --> true, file exists
- before executing the read file, event loop runs some other asynchronous code that removes/renames the file
- ...original code resumes, and now fails, since file is no longer available
These sporadically cause some problems. Therefore, it is best to get rid of most of the "unnecessary" `pathExists` calls.
And it is also somewhat slower to first check the file existence and then read it than directly read it. However, we are talking …
=> INTDEV-817 Remove unnecessary 'pathExists' calls

.github/workflows/build-and-test-windows.yml, .github/workflows/build-and-test.yml, pnpm-lock.yaml, tools/cli/src/index.ts, tools/data-handler/package.json, tools/data-handler/src/command-handler.ts, tools/data-handler/src/commands/create.ts, tools/data-handler/src/commands/import.ts, tools/data-handler/src/commands/remove.ts, tools/data-handler/src/commands/show.ts, tools/data-handler/src/containers/project.ts, tools/data-handler/src/interfaces/project-interfaces.ts, tools/data-handler/src/module-manager.ts, tools/data-handler/src/project-settings.ts, tools/data-handler/test/command-handler-import.test.ts, tools/data-handler/test/command-handler-show.test.ts, tools/data-handler/test/module-manager.test.ts, tools/data-handler/test/project.test.ts, tools/data-handler/test/resources.test.ts, tools/data-handler/test/show.test.ts, tools/schema/cardsConfigSchema.json
Means to add / remove and update modules from CLI. 
Changes to commands: 
* `cyberismo add module <name>`
* `cyberismo remove module <name>`
New command:
* `cyberismo update-modules`
Modules are now stored into an array in `cardsConfig.json`. Each module can be either from file system (starting with `file:`), or from git (starting with `https`). Once add command is given, the location (url or path) is written to project configuration. The name of the module is automatically fetched from module's  own configuration prefix. There is no support for importing a module with a different name. Removal works with prefixes as well; module must be of course imported first. When running an update, it will make local copies of modules to `.temp` and then remove the existing and copying the temp-copy …
=> INTDEV-802 Controlling modules in a project

tools/data-handler/src/commands/calculate.ts, tools/data-handler/src/commands/move.ts, tools/data-handler/src/commands/show.ts, tools/data-handler/src/commands/validate.ts, tools/data-handler/src/containers/project.ts, tools/data-handler/src/resources/field-type-resource.ts, tools/data-handler/src/resources/file-resource.ts, tools/data-handler/src/utils/clingo-fact-builder.ts, tools/data-handler/src/utils/clingo-facts.ts, tools/data-handler/test/project.test.ts, tools/schema/cardTreeDirectorySchema.json
Add facts from modules, reports and templates.
I decided to rename the current logo program file `modules.lp` to `calculations.lp` since the file actually collect the separate calculation files from modules. The new `modules.lp` contain the facts from the modules (basically names and prefixes).
=> INTDEV-773 Create calculation files for modules, reports and templates

tools/data-handler/src/module-manager.ts, tools/data-handler/test/module-manager.test.ts
Adding even empty string for `username` and `password` (read: token) makes `git` to treat them as defined. This leads to a situation where when user did not had the environment variables (`CYBERISMO_GIT_USER` and `CYBERISMO_GIT_TOKEN`) defined, they are passed on as empty strings and then they are assumed to be the username and the token for this query. Which then leads to 401. 
Changing the implementation so that only if both environmental variables are defined, then they are added to the git url. 
Now for example adding a private repo module without credentials works correctly (i.e. you cannot do it):
=> INTDEV-844 Allow public repos to be updated without username and token

resources/calculations/common/main.lp
When https://github.com/CyberismoCom/cyberismo/pull/594 was done, there was a rename of `lp`-files.
Existing `modules.lp` was renamed to `calculations.lp` and a new `modules.lp` was included in the fact generation.
Unfortunately, the `calculations.lp` was not included in the clingo program.
Adding the missing import.
=> Add missing import statement

tools/backend/src/routes/cards.ts
Environment variable needed for report macros. Application worked fine when started without cyberismo app -p <project> flag, but did not resolve path properly when -p flag was used. This environment variable was left empty when Next.js was taken out, since it was set during the initialization of next.js server
=> Add missing projectPath to env variable

tools/data-handler/test/resources.test.ts
Calculate.ts loads the logic programs at the beginning when the calculate class is loaded, which causes a delay large enough to cause a timeout delay
=> Increase timeout threshold

resources/calculations/common/base.lp
- Fix a bug in the existing ancestor rule
- Add ancestor rules for templates, where the highest level parent is the template itself
=> Fix the logic program rule for ancestor

tools/data-handler/src/commands/export-site.ts
The original problem is two-fold: 
1) We have custom root item that is basically a list xrefs, it is not an actual card and is only displayed in side-nav.
2) Thus, the "root" of the breadcrumb is empty. The Antora automatically makes the root to point to `/cards/index.html` but our root index resides one level higher at `/index.html`.  This is to ensure that `<domain>.com` URLs are rendered correctly.
To work around these limitations, write an additional `index.html` to `cards` directory, that only makes a refresh to parent card.
=> INTDEV-840 Make breadcrumb root point to root-card

tools/app/src/components/LoadingGate.tsx
As we already have `Loading...` text, use it from translation file, instead of hard coded string.
=> Use translated loading text instead of hard coded

tools/data-handler/src/commands/validate.ts, tools/data-handler/src/utils/schemas.ts, tools/data-handler/test/0_validate.test.ts
As suggested in https://github.com/CyberismoCom/cyberismo/pull/619 by @samutoljamo-pareto , we should use the imported schemas instead of reading them (again!) from disk. 
Noticed that few of the schemas were missing from imports --> added those.
Also made the first validate test such that it shows what is wrong with validation in test results.
=> INTDEV-849 Use the imported schemas instead of reading them from disk

tools/cli/src/index.ts, tools/data-handler/src/command-handler.ts, tools/data-handler/src/commands/show.ts, tools/data-handler/test/command-handler-report.test.ts, tools/data-handler/test/command-handler-show.test.ts, tools/data-handler/test/project.test.ts, tools/data-handler/test/show.test.ts, tools/data-handler/test/test-data/valid/decision-records/.cards/local/reports/anotherReport.json, tools/data-handler/test/test-data/valid/decision-records/.cards/local/reports/anotherReport/.schema, tools/data-handler/test/test-data/valid/decision-records/.cards/local/reports/anotherReport/index.adoc.hbs, tools/data-handler/test/test-data/valid/decision-records/.cards/local/reports/anotherReport/parameterSchema.json, tools/data-handler/test/test-data/valid/decision-records/.cards/local/reports/anotherReport/query.lp.hbs
Add new command `report` that enables running reports from CLI. 
Command requires that a parameters file is provided as an input data and there is optional `outputFile` is results are wanted to had into a file instead of stdout. 
**Note** that I created a new branch (and PR) for this, since previous was using wrong JIRA ID.
=> INTDEV-549 Show report results from CLI

pnpm-lock.yaml, tools/app/src/components/ContentArea.tsx, tools/app/src/components/modals/svgViewerModal.tsx, tools/app/src/globals.css, tools/data-handler/package.json, tools/data-handler/src/command-handler.ts, tools/data-handler/src/commands/calculate.ts, tools/data-handler/src/macros/index.ts, tools/data-handler/src/utils/sanitize-svg.ts
- Clingraph images are now SVG format
- New open full screen and download buttons added to every graph
- New modal to view the SVG
- Modal supports mouse move, zoom, backpedal, etc. basic functionalities
- Export support kept with environment variable that will:
- Import sanitized regular adoc svg image for exports
- Import sanitized raw SVG for gui
OPEN THINGS:
- Name of the SVG when downloaded is Diagram.svg, how we make this better?
=> Add SVG based graph support

LICENSE, resources/calculations/common/base.lp, resources/calculations/common/main.lp, resources/calculations/common/pythonFunctions.lp, resources/calculations/common/queryLanguage.lp, resources/calculations/queries/card.lp, resources/calculations/queries/onCreation.lp, resources/calculations/queries/onTransition.lp, resources/calculations/queries/tree.lp
Remove the previously added copyright blocks.
Extend license to cover the files with additional note instead.
=> INTDEV-851 Remove copyright comment blocks from .lp

tools/cli/src/index.ts, tools/data-handler/src/command-handler.ts, tools/data-handler/src/commands/import.ts, tools/data-handler/src/interfaces/project-interfaces.ts, tools/data-handler/src/module-manager.ts, tools/data-handler/test/module-manager.test.ts, tools/schema/cardsConfigSchema.json
Implementation now supports both public and private repositories for modules. 
It is assumed that module is public; if there is need for private repository access, then the project importing that modules needs to defined in `cardsConfig.json` that module is private with `"private": true`.
Credentials need to be provided through `.env` or with environmental variables.
Additionally, clarified the output from `update modules` command so that it is clear which repository is being used. 
Finally, added a possibility to add private repo directly (no need to manually edit `cardsConfig.json`) with 
`cyberismo import module <https> [useCredentials]` option.
**Note** that multiple private repository locations are not currently supported.
=> INTDEV-850 Support both private and public repos with modules

tools/cli/src/index.ts, tools/cli/test/cli.test.ts
Added a test for `cyberismo calc run`. Tested that it broke without the fix, which is already in main. Also added a deprecated warning to `cyberismo calc generate`, because it should be removed. But it will still provide a 0 exit code so that it does not break existing CIs
=> INTDEV-852 Cyberismo calc testing

tools/app/src/lib/slices/notifications.ts, tools/app/src/lib/swr.ts, tools/app/src/pages/card-view.tsx, tools/app/src/pages/layout.tsx
Now for errors, autohide duration is 10 seconds. If you click anywhere(after at least 2 seconds), it will simply hide the error.
Also errors will be shown as is from DH
=> INTDEV-839 adjust notification hiding

tools/app/src/lib/swr.ts
The previous commit had a lint issue and since the lint commit was not rebased to that, CI failed in main
=> fix lint error

tools/app/eslint.config.mjs
Linting through coverage test results causes unwanted lint warnings:
=> Do not lint coverage test results

tools/data-handler/src/project-settings.ts, tools/data-handler/test/command-handler-import.test.ts
When module was imported from local filesystem and was using relative path, the actual path in the original import command was stored to be module location. 
E.g. calling from `/user/home` with command: `cyberismo import module ./module-own` would have stored module `location` to be `./module-own`. This would then have failed all module related commands (e.g. `update-modules`) when they are run from any other directory. 
Modified the import unit tests to run `update-modules` after tests have performed import command.
=> INTDEV-857 Resolve module path to the project settings

tools/data-handler/src/resources/array-handler.ts, tools/data-handler/src/resources/card-type-resource.ts, tools/data-handler/src/resources/field-type-resource.ts, tools/data-handler/src/resources/file-resource.ts, tools/data-handler/src/resources/workflow-resource.ts, tools/data-handler/test/resources.test.ts
This change enables operations like: 
State rename:
`cyberismo update cisms/workflows/page change states "{\"name\": \"Approved\", \"category\":\"closed\"}" "{\"name\": \"ApprovedNew\", \"category\":\"closed\"}"` 
--> Renames 'Approved' state to 'ApprovedNew' and updates all cards using the state.
State removal: 
`cyberismo update cisms/workflows/page remove states "Approved"`
--> Removes 'Approved' state. Cards using the state are not updated, as there is no replacement value given. It is assumed that the user knows what he/she is doing. User needs to update cards him/herself with valid value(s).
or with replacement value: 
`cyberismo update cisms/workflows/page remove states "Approved" "{\"name\": \"Deprecated\", \"category\": \"closed\"}"`
--> Removes 'Approved' state and replaces …
=> INTDEV-579 Allow renaming or removing workflow states with update

pnpm-lock.yaml, tools/data-handler/package.json
Dompurify node module currently includes types too, so there is no need to have separate types dependency.
See more from: https://www.npmjs.com/package/@types/dompurify
=> Remove deprecated @types/dompurify

tools/cli/src/index.ts, tools/data-handler/src/card-metadata-updater.ts, tools/data-handler/src/command-handler.ts, tools/data-handler/src/command-manager.ts, tools/data-handler/src/commands/calculate.ts, tools/data-handler/src/containers/project/project-paths.ts, tools/data-handler/src/containers/template.ts, tools/data-handler/src/macros/graph/index.ts, tools/data-handler/src/utils/clingo-fact-builder.ts, tools/data-handler/src/utils/log-utils.ts
Moved logs under the project to `<project_path>/.logs/dh.log`
By default, DH won't log to stdout, but the logs can be enabled with `-L debug|info|trace etc...`. Regardless of configuration, all logs(including trace) are logged to the file. The logs are in pino's json format, but they can be viewed like so: `cyberismo app -L trace | npx pino-pretty`
Also made a few small improvements to logging, but nothing major. Now we should start simply using the logger more. I removed the countless clingo traces, as there is no benefit to logging every single query / response given by clingo if there are no errors.
=> INTDEV-859 Move logs under project

tools/backend/src/export.ts, tools/cli/src/index.ts, tools/data-handler/src/command-handler.ts, tools/data-handler/src/command-manager.ts, tools/data-handler/src/containers/project.ts, tools/data-handler/src/containers/project/project-content-watcher.ts, tools/data-handler/src/resources/card-type-resource.ts, tools/data-handler/src/utils/resource-utils.ts, tools/data-handler/test/utils/resource-utils.test.ts
Added a file watcher for running concurrent instances of a project on same machine. 
This will not work in Docker and is not intended to.
To avoid watching the filesystem unnecessarily (normal case), there is an additional flag for `cyberismo app` `--concurrent-apps` which causes the instance to watch changes in `.cards/local`. Module changes are not watched, as they should not be modified. File renames are ignored. 
When a file change is noticed, it is checked if a resource file was changed. If so, then resource is removed from cache and recreated. Then pushed into cache again.
=> INTDEV-845 Update cache values when data changes

tools/app/src/routes.ts
For now, let's add this workaround so we can get cyberismo docs to work. 404.html page on github will redirect from `/*` to `/?/*` and then on react we will convert that path back, without doing another request
=> INTDEV-907 Add workaround for static sites

package.json
npm / pnpm wants us to specify public so that we do not accidentally publish private packages
=> Add access public to publish script

.github/workflows/build-and-test-windows.yml
Turn off `safe-directory` for GitHub Windows build action.
The configuration value for git is described here: https://git-scm.com/docs/git-config
In short, it ensures that used directory can be used by any user. 
Why the setting makes cloning directory "slow" in CI/Windows is uncertain. However, it seems to be rather common fix for these kinds of issues in Windows builds in GitHub.
=> Turn off 'safe-directory' for CI/Windows build action

.github/workflows/publish.yml, tools/assets/package.json, tools/backend/package.json, tools/cli/package.json, tools/data-handler/package.json, tools/node-clingo/package.json
Allthough pnpm determines that package A is a dependency of package B and thus knows to build A before B, it does not work when we use build in a prepublish script if we only publish B instead of A.
=> Fix release CI

tools/data-handler/src/commands/create.ts
Because the string was a multi-line string, the indentation was also visible on the generated `.gitignore`. Added also `.temp`, `.cache` and `.logs` folders. Unsure what creates the `.cache` folder, but let's add it for now. Might be also useful in the future.
=> INTDEV-919 Fix indentation of .gitignore and add folders to it

tools/data-handler/test/module-manager.test.ts
Let's turn the test off on CI/Windows since it seems to be rather troublesome.
=> Skip git module cloning test on CI/Windows due to fluctuation

tools/data-handler/src/commands/remove.ts, tools/data-handler/src/containers/project.ts, tools/data-handler/src/module-manager.ts, tools/data-handler/test/command-handler-import.test.ts
Two new mini-features:
1) If a removed module is still used by other modules, it is only removed from project configuration (`cardsConfig.json`). The files are left on `.cards/modules` as long as they are still used by other modules.
2) If removing a module would lead to a situation where another module would become orphaned (= it is no longer needed by any other module), it is removed as well.
Implementation builds a dependency graph of module-dependencies when one is tried to be removed. Since there are always rather limited amount of modules (some dozens at max), the dependency graph can be built whenever the operation starts; it won't take that long (maybe few ms if you have slow disk). 
Then using the graph, it deduces if it can remove the module and are there any orphans left …
=> INTDEV-897 Smarter 'removeModule' support

tools/data-handler/src/commands/validate.ts, tools/data-handler/test/0_validate.test.ts
There was an unused method `validateSchema` in `Validation`. 
The `Validation-utils` method `validateJson<T>` basically does the same thing.
Removing the function.
=> Remove unused method from Validation

tools/data-handler/src/containers/project/resource-collector.ts
Instead of deny-listing all sorts of file names, only accept JSON and LP files as potential resource files.
=> INTDEV-934 Only accept JSON and LP files as potential resource files

tools/assets/src/graphvizReport/query.lp.hbs
Two rules were missing in the Graphviz query:
- There was no rule to put edges that did not specify a graph to the `default`graph, if the edge had an identifier (3-tuple edge)
- Attributes of edges that do not have an identifier (2-tuple edges) did not work, as we did not have a rule to yield the same attribute for a 3-type edge with `""` as its identifier
=> INTDEV-952 Fix edge handling in Graphviz query

tools/app/src/pages/cards/card-edit.tsx
Scroll was triggered also after each time a card had loaded. Also checked whether this bug was present in normal view, but it was not.
=> INTDEV-908 trigger scroll only after tab changes or during the initial load in edit view

pnpm-lock.yaml, tools/data-handler/package.json, tools/data-handler/src/macros/index.ts, tools/data-handler/src/macros/scoreCard/index.ts, tools/data-handler/src/svg/index.ts, tools/data-handler/src/svg/lib.ts, tools/data-handler/src/svg/scoreCard.ts, tools/data-handler/src/types/string-pixel-width.d.ts, tools/data-handler/test/macros/index.test.ts
Score cards were using html syntax and as part of wanting to use `asciidoctor-pdf`, we cannot use html based components or we need have 2 separate implementations. In this case, I used svg for implementing the score card. Some restrictions:
* Rendering now happens in DH instead of App. Generally this is a bad idea. Might be smart to create some kind of common package that shared between DH and App, which would allow the app to render it. Development would be nicer if we used e.g. react to make the template instead of actually string(it can still be rendered on the server)
* Layout depends on estimating size of text(we could get a more accurate estimation by actually rendering the svg and checking its size, but I don't think that's needed)
* The svg is not responsive, but app does not work …
=> INTDEV-922 implement SVG score card generation

.github/workflows/build-cyberismo-app-image.yml
It simply checks if the commit before had a different version. If yes, triggers docker build(on main). Version tags have also been added in addition to having the latest tag:
`latest`=most recent version
`x`=receive all updates for major versions(i.e. cyberismo:1 will not update to version 2)
`x.y`=receive all updates for a specific minor version(in other words patches)
`x.y.z`=use a specific version.
=> Build docker on version change and version containers

pnpm-lock.yaml, tools/data-handler/src/command-handler.ts, tools/data-handler/src/commands/calculate.ts, tools/node-clingo/README.md, tools/node-clingo/binding.gyp, tools/node-clingo/lib/index.ts, tools/node-clingo/package.json, tools/node-clingo/src/binding.cc, tools/node-clingo/test/solve.test.ts
We add context by setting each logic program for each resource separately. To make adding logic program to solves easier, I created a system where:
* Each program has a key(e.g. `base/fieldTypes/myFieldType`
* Each program may have flags(e.g. `resources` or `main`)
When you want to solve something, you may use flags or keys to add logic programs. Currently we only have flag `main`, which adds every single logic program there is.
For example, if there is an exception in some calculation:
Our exception handling was quite complex as we had NAPI on no-exception mode while we had c++ exceptions enabled. After upgrading NAPI to a newer version, I started using NAPIs `except_all` target, which catches std exceptions too so we do not have to add the boilerplate try catch for all functions.
=> INTDEV-924 Add context to logic programs

tools/backend/eslint.config.js, tools/backend/package.json, tools/backend/src/domain/cards/index.ts, tools/backend/src/domain/cards/lib.ts, tools/backend/src/domain/cards/service.ts, tools/backend/src/domain/fieldTypes/service.ts, tools/backend/src/domain/linkTypes/service.ts, tools/backend/src/domain/resources/service.ts, tools/backend/src/domain/templates/service.ts, tools/backend/src/domain/tree/service.ts, tools/backend/src/export.ts, tools/backend/src/middleware/commandManager.ts, tools/backend/src/utils.ts, tools/backend/test/api.test.ts, tools/backend/test/export.test.ts, tools/backend/test/resources.service.test.ts, tools/node-clingo/eslint.config.js, tools/node-clingo/lib/index.ts, tools/node-clingo/lib/node-gyp-build.d.ts, tools/node-clingo/package.json, tools/node-clingo/scripts/collect-prebuilds.js, tools/node-clingo/scripts/download-prebuild.js, tools/node-clingo/test/solve.test.ts
Enable listing for 'node-clingo' and 'backend' sub-projects.
It might be good idea to define the interfaces for the backend methods instead of using `unknown`.
=> INTDEV-954 Enable linting for 'backend' and 'node-clingo'

.clang-format, .github/codeql-config.yml, .github/workflows/codeql.yml, .github/workflows/cpp-quality.yml, scripts/pre-commit.sample.txt, tools/node-clingo/package.json, tools/node-clingo/src/binding.cc, tools/node-clingo/src/function_handlers.cc, tools/node-clingo/src/function_handlers.h, tools/node-clingo/src/helpers.cc, tools/node-clingo/src/helpers.h
C++ code in `tools/node-clingo` is now analysed by the GitHub. It also checks that code is formatted. 
C++ code formatting is now using Clang formatter. The rules are supporting older version of Clang formatter, to make the installation simpler for all platforms. 
I tried to avoid formatting the existing code as little as possible.
The base C++ style is now based on LLVM (I think it was closest for existing code base).
However I made two small styling decisions : 
1) Pointer and reference are part of the type, and not name
E.g.  `int* pointer;` instead of `int *pointer;`
IMHO it makes no sense to attach the information to the variable name,
2) Enforced whitespace before a control command (`if`, `switch`, `for` ...)
E.g.  `if (test)` instead of `if(test)`
IMHO improves code readability. …
=> INTDEV-955, INTDEV-933 C++ code formatting and analysis

.github/workflows/build-and-test-macos.yml, .github/workflows/build-and-test-windows.yml, .github/workflows/build-and-test.yml, .github/workflows/publish.yml, .github/workflows/test-pr-docker.yml
All actions are now pinned to specific commit SHAs, which prevents supply chain attacks where malicious actors could potentially:
* Move version tags to point to compromised code 
* Inject backdoors or malicious code into popular GitHub Actions
The original version is still kept in a comment for human readers. 
This fixes issues 116-124 from https://github.com/CyberismoCom/cyberismo/security/code-scanning
=> SECURITY FIX: Pin actions to specific commit SHAs instead of labels

tools/app/src/components/macros/CreateCards.tsx
Previously params where passed as html attributes and they were lowercased by the html parser. Now that we use base64 encoded parameters, the capitalization is preserved
=> INTDEV-973 Use camelcase in UI macros

tools/cli/src/index.ts, tools/data-handler/src/command-handler.ts, tools/data-handler/src/commands/update.ts, tools/data-handler/src/resources/card-type-resource.ts, tools/data-handler/src/resources/file-resource.ts, tools/data-handler/src/resources/folder-resource.ts, tools/data-handler/src/resources/resource-object.ts, tools/data-handler/test/command-handler-update.test.ts
Allow `update` command to change `workflow` in a card type. 
This causes all cards that are using the card type to be changed to a new state according to the state mapping table provided. 
The implementation uses a new parameter on CLI that is provided with a flagged parameter to a local file. The file should have just single property `stateMapping` object having keys for each current state and value for those to match new states. 
Before changing the `workflow` value, it is checked that all states in the current workflow are mapped to new states, and that there are no invalid new states (that do not exist in the upcoming workflow). 
**Additionally** 
1) Changed `update` implementation so that if not a JSON value is given as `target`, it defaults to string (previously it would have just …
=> INTDEV-582 Change 'workflow' in card type

tools/assets/src/schema/cardsConfigSchema.json
The `descriptions` of multiple properties of `modules` are outdated since SSH support was added.
Clarify with better descriptions.
On a hindsight the whole object should have been defined as: 
```
"modules": {
"description": "List of modules that have been included in the project",
"type": "array",
"items": {
"type": "object",
"properties": {
"name": {
"description": "Module name (project prefix). Must be unique.",
"type": "string"
},
"gitLocation": {
"description": "Git remote URL",
"type": "string"
},
"fileLocation": {
"description": "Relative file reference",
"type": "string"
},
"branch": {
"description": "Defines git branch. If empty, uses repository default branch'. ",
"type": "string"
},
"private": {
"description": "If true, the module is private and requires credentials …
```
=> INTDEV-984 Clarify modules 'properties' descriptions

tools/backend/src/domain/cards/lib.ts, tools/data-handler/src/commands/show.ts, tools/data-handler/src/interfaces/macros.ts, tools/data-handler/src/macros/base-macro.ts, tools/data-handler/src/macros/createCards/index.ts, tools/data-handler/src/macros/graph/index.ts, tools/data-handler/src/macros/include/index.ts, tools/data-handler/src/macros/percentage/index.ts, tools/data-handler/src/macros/report/index.ts, tools/data-handler/src/macros/scoreCard/index.ts, tools/data-handler/src/macros/vegalite/index.ts, tools/data-handler/test/macros/index.test.ts
We have a problem: For now, we've only had 2 modes(excluding `validate`), which are `static` and `inject`. Static was meant to be used when only adoc is usable while inject was meant to be used for app, which supports html. However, the new static site falls between these: It could render content just like app can, but it's content is static so we do not want to render the `createCards` button.
So I added I third mode: `exportSite`. I feel like the naming is a bit confusing and it would probably be a better idea to simply move on to using `context` also in macros. Now we have both the mode and context, which also partially overlap.
=> INTDEV-987 Fix xref in export site

tools/assets/src/calculations/common/queryLanguage.lp, tools/assets/src/calculations/common/utils.lp, tools/assets/src/calculations/queries/card.lp
This also seems to fix INTDEV-956. After using normal fields for displaying more complex content like enums, notifications etc, clingo seemed to slow down significantly. I think one of the main issues is that we were using broad select facts, which caused unnecessary logic that had to be handled by clingo. Select does make sense for accessing properties that are part of the data, but having to use select for fields that only part of a specific query is unnecessarily complex. Thus, I added an extension to `showField`:
`showField(Key, Field, Value, DataType)` allows skipping select checks and results in a `#show field(Key, Field, Value, DataType)`. Similarly to `fields`, `showFields` allows specifying multiple fields directly. I recommend that `showField` should replace all cases, where a …
=> INTDEV-947 use show more directly

.github/workflows/build-and-test-macos.yml, .github/workflows/build-and-test-windows.yml, .github/workflows/build-and-test.yml, .github/workflows/prebuild.yml, .github/workflows/publish.yml, .github/workflows/test-pr-docker.yml
Instead of defining nodeJS version each time it is required by GitHub workflows, define the variable once and re-use the variable from all other places. 
Variable has been defined to : Settings - Secrets and variables - Actions - Variables tab as `NODE_VERSION` and its value has been set to `22.x`. This works as long as we are using workflows from one repository only. Once we have multiple repositories, the value needs to be defined on organisational level.
=> INTDEV-960 Define nodeJS version in only one place

tools/data-handler/src/commands/create.ts, tools/data-handler/src/commands/remove.ts, tools/data-handler/src/commands/rename.ts, tools/data-handler/src/resources/workflow-resource.ts, tools/data-handler/test/command-handler-import.test.ts
Fixed one unit test that periodically failed on local system (MacOS). The test was fixed by removing the `.then()`  part and instead just `await` the result of the first call before subsequent calls. 
But this test actually revealed a potential error in project creation when it writes JSON files. Used `forEach` with `async` callback to write JSON config files, causing the function to return before all files were written. Fixed by changing to `Promise.all` with `map`. 
Similar fixes were applied to three other places:
1) In card removal, there was a bit dubious `filter` (the return value was ignored)  and `async` callback, whereas in reality each filtered value was just put into a `Promise` container. 
2) In replace operation, `forEach` was potentially returning before all file operations …
=> INTDEV-1004 - Fix fluctuating unit test

.github/dependabot.yml, package.json, pnpm-lock.yaml, tools/backend/eslint.config.js, tools/backend/src/main.ts, tools/cli/eslint.config.js, tools/cli/src/index.ts, tools/data-handler/eslint.config.js, tools/data-handler/src/card-metadata-updater.ts, tools/data-handler/src/commands/create.ts, tools/data-handler/src/containers/project.ts, tools/data-handler/src/macros/index.ts, tools/data-handler/src/resources/field-type-resource.ts, tools/data-handler/test/macros/index.test.ts, tools/data-handler/test/resources.test.ts
Add more rules and warnings related to promises.
Code that caused promise-plugin to nag is fixed in a separate commit. 
I set the `'promise/always-return'` to `off` since it was nagging from all `Promises` without `returns`; even `Promise<void>` ones. Thus, whole lot of new lines with `return;` would have been needed. If reviewers disagree, let's discuss.
=> Enable ESLint promise checks

pnpm-lock.yaml, tools/app/cypress.config.ts, tools/assets/src/hub/moduleList.json, tools/assets/src/schema/hubSchema.json, tools/assets/src/schemas.ts, tools/cli/package.json, tools/cli/src/index.ts, tools/cli/src/resource-type-parser.ts, tools/cli/test/cli.test.ts, tools/data-handler/src/command-handler.ts, tools/data-handler/src/command-manager.ts, tools/data-handler/src/commands/create.ts, tools/data-handler/src/commands/fetch.ts, tools/data-handler/src/commands/index.ts, tools/data-handler/src/commands/remove.ts, tools/data-handler/src/commands/show.ts, tools/data-handler/src/commands/validate.ts, tools/data-handler/src/containers/project.ts, tools/data-handler/src/interfaces/project-interfaces.ts, tools/data-handler/src/project-settings.ts, tools/data-handler/test/command-handler-add.test.ts, tools/data-handler/test/command-handler-fetch.test.ts, tools/data-handler/test/command-handler-import.test.ts, tools/data-handler/test/command-handler-remove.test.ts, tools/data-handler/test/command-handler-show.test.ts
**New commands**
`cyberismo show module hub` - lists hubs in the project. Existing projects will not have any until a hub has been added.
`cyberismo add hub <location>` - adds a new URL location as a hub 
`cyberismo remove hub <location>` removes a hub from the project
`cyberismo fetch hubs` - fetches module information from already added hubs to local filesystem (to a temporary file `.temp/moduleList.json`). 
`cyberismo show importableModules` - shows module names that have not yet been imported to the project.
Hubs should have a means to retrieve JSON file (`moduleList`) from an URL. The file should implement the JSON schema `hubSchema`. 
**Changed commands**
`cyberismo show project` - will show hub details also
`cyberismo import` - if given without a parameter will automatically prompt …
=> INTDEV-837 Interactive module installation

tools/assets/src/calculations/common/queryLanguage.lp
The actual issue was the missing "Value" variable from resultFields, but at the same time I added some negations to make sure the rules do not overlap
=> INTDEV-1026 Fix overlapping enum/list resultFields

.github/workflows/prebuild.yml, tools/cli/src/index.ts, tools/data-handler/src/command-handler.ts, tools/data-handler/src/commands/calculate.ts, tools/data-handler/src/containers/project/calculation-engine.ts, tools/node-clingo/binding.gyp, tools/node-clingo/lib/index.ts, tools/node-clingo/package.json, tools/node-clingo/src/binding.cc, tools/node-clingo/src/function_handlers.cc, tools/node-clingo/test/solve.test.ts
Adds possibility of generating a logic program to a file through CLI. It is mostly useful to us as it is easier to inspect clingo programs by executing them manually.
Syntax:
`cyberismo calc generate <file name> [query]`
where query is a pre-existing query such as `tree` or `card`. This is useful for inspecting perf of said queries. If no query is specified, it will append the whole global program to the file without any queries.
=> INTDEV -956 Allow exporting logic programs

.github/dependabot.yml
Since some of the react dependencies are connected to each other (cannot update one unless the other is updated as well), move at least some of the React related dependencies to be updated with one PR. This will also lower the amount of PRs that the Dependabot creates.
=> Make react dependency group

.github/workflows/build-and-test-macos.yml
Do not build MacOS for every rebase and every PR. 
Weekly build should be sufficient (MacOS basically should build if Linux builds).
=> Build MacOS only every week

tools/data-handler/test/command-show.test.ts
Noticed that `show importableModule all - success()` sometimes failed in CI. 
Implemented better `beforeEach` that ensures that importable modules are actually fetched and usable before tests are run.
As this can be slower than earlier tests, added 30s timeout. 
Also noticed that there were few garbage `expect` calls related to array length that didn't actually work. Fixed those too.
=> Fix flaky test to use importable modules results correct way 

tools/cli/src/index.ts, tools/cli/test/cli.test.ts
Shows version information by using: `cyberismo show version`. 
For now, only singular version (data-handler's) is shown in the received object.
In the future, we can expand this with other sub-projects (though they should share same version name) and versions of the data (if we make data versional apart from binary version) and used modules.
=> INTDEV-1015 CLI: Show version command

tools/app/src/components/modals/NewCardModal.tsx, tools/backend/src/domain/resources/service.ts, tools/backend/test/api.test.ts, tools/cli/src/index.ts, tools/data-handler/src/commands/show.ts, tools/data-handler/src/containers/card-container.ts, tools/data-handler/src/interfaces/folder-content-interfaces.ts, tools/data-handler/src/interfaces/resource-interfaces.ts, tools/data-handler/src/macros/report/index.ts, tools/data-handler/src/resources/folder-resource.ts, tools/data-handler/src/resources/graph-model-resource.ts, tools/data-handler/src/resources/graph-view-resource.ts, tools/data-handler/src/resources/report-resource.ts, tools/data-handler/src/resources/template-resource.ts, tools/data-handler/test/command-edit.test.ts, tools/data-handler/test/command-show.test.ts, tools/data-handler/test/resources.test.ts, tools/data-handler/test/template.test.ts
Add new property `content` for folder based resources (except `template` which has cards, and have its own APIs for handling them). 
Content for each folder resource can be seen through using `show()` and changed through `update()`. 
Accessing certain known content type uses well-known names (e.g. `schema`, `templateContent`). 
Interfaces for the folder resources have been modified. Report has been standardised not to have double `displayName` and `description` properties visible when using `show()`.  There are APIs in place (for internal use) that map well known names to actual filenames and vice versa. 
For example, to update the Graph Model calculations (in file 'model.lp'), one would call:
```
const res = new GraphModelResource(
project, …
```
=> INTDEV-1007 Use resource content through existing resource APIs

tools/app/src/globals.css
Tested at least with 16:9 aspect ratio Vimeo embed.
Unfortunately, the CSS is dependent on a fixed aspect ratio. But this is better than nothing, I suppose.
=> INTDEV-1034 Make video blocks full width
