tools/data-handler/src/calculate.ts
Improve calculation generation performance, when new cards are added to the project (via `create cards <template>`).
Change the implementation so that the file including the card specific logic programs, is written once; after all of the individual card specific calculation files are generated. Additionally, always generate the whole tree, instead of trying to generate card-by-card subtrees. The latter caused that cards sharing same subtrees would generate their logic files repeatedly (as many times as there were cards sharing the same ancestor).
This will improve the performance drastically:
- with some thousands of cards, the generation takes less than second, instead of minutes
- with 20000 cards, generation takes roughly two seconds, instead of hours
These values are from MacBook Pro …
=> INTDEV-333 - Improve calculations generation perf as cards are added

package-lock.json, tools/app/app/api/cardtypes/[key]/route.tsx, tools/app/app/api/fieldtypes/route.tsx, tools/app/app/cards/[key]/edit/page.tsx, tools/app/app/cards/[key]/page.tsx, tools/app/app/components/EditableField.tsx, tools/app/app/components/ExpandingBox.tsx, tools/app/app/components/FieldEditor.tsx, tools/app/app/lib/api/cardtype.ts, tools/app/app/lib/api/common.ts, tools/app/app/lib/api/fieldtypes.ts, tools/app/app/lib/api/index.ts, tools/app/app/lib/api/types.ts, tools/app/app/lib/components.ts, tools/app/app/lib/definitions.ts, tools/app/app/lib/swr.ts, tools/app/app/lib/utils.ts, tools/app/app/locales/en/translation.json, tools/app/app/theme.ts, tools/app/package.json
* Metadata is visible when viewing a card. "key" and "cardtype" are always visible and so are fields specified by "alwaysVisibleFields".
* Metadata is editable in edit view. In edit view, it is minimized by default. 
* react-hook-form module was added and used for the form.(It is a small widely used no-dependency package which removes boilerplate code around forms, no effect on the UI itself)
=> INTDEV-315 Edit metadata in edit view and view metadata

tools/app/app/api/cards/[key]/route.tsx, tools/app/app/cards/[key]/edit/page.tsx, tools/app/app/cards/[key]/page.tsx, tools/app/app/components/ContentArea.tsx, tools/app/app/components/EditableField.tsx, tools/app/app/components/ExpandingBox.tsx, tools/app/app/components/FieldEditor.tsx, tools/app/app/lib/api/types.ts, tools/app/app/lib/components.ts, tools/app/app/lib/definitions.ts, tools/app/app/lib/utils.ts, tools/data-handler/src/interfaces/project-interfaces.ts
Added the following improvements:
* Changed order of title / metadata
* Display enum / boolean display values instead of the underlying value
* Make the edit widgets wider
* More robust dataflow
* Do not render anything if there are no elements
=> INTDEV-357 improve metadata editing

tools/app/app/api/cards/[key]/route.tsx, tools/data-handler/src/containers/card-container.ts, tools/data-handler/test/edit.test.ts
Allows empty string as asciidoc content
=> INTDEV-346 allow empty content

tools/app/app/components/AppToolbar.tsx
* Removed cards from title
* Removed Imports modules
* Commented out "new card"
=> INTDEV-342 modify navbar

tools/data-handler/src/command-handler.ts
Re-do this PR again. It was lost in recent merge.
=> INTDEV-361 Make 'createProject()' use its own sanity checks

tools/app/app/cards/page.tsx, tools/app/app/locales/en/translation.json
Show "Project is empty" rather than "Select a card" if project doesn't have cards
=> INTDEV-303 display different text for user when project is empty

tools/data-handler/src/containers/project.ts
Remove unnecessary getter. There is another getter that provides the same path.
=> Remove unnecessary function

package-lock.json, tools/app/app/cards/[key]/edit/page.tsx, tools/app/app/cards/layout.tsx, tools/app/package.json
Replace default text area by a CodeMirror component. AsciiDoc mode for CodeMirror is provided by Asciidoctor.
Also fix a dependency vulnerability found by npm audit.
=> INTDEV-344: Use CodeMirror to edit AsciiDoc content

tools/app/app/api/cards/[key]/route.tsx, tools/app/app/api/templates/route.tsx, tools/app/app/cards/layout.tsx, tools/app/app/components/AppToolbar.tsx, tools/app/app/components/NewCardDialog.tsx, tools/app/app/components/TreeMenu.tsx, tools/app/app/layout.tsx, tools/app/app/lib/api/card.ts, tools/app/app/lib/api/common.ts, tools/app/app/lib/api/index.ts, tools/app/app/lib/api/templates.ts, tools/app/app/lib/api/types.ts, tools/app/app/lib/swr.ts, tools/app/app/lib/utils.ts, tools/app/app/locales/en/translation.json
Added ability to create cards using templates
=> Add create card functionality

tools/app/app/components/StateSelector.tsx
Allows users to make transitions, which do not change the state
=> Allow transition to self

tools/app/__tests__/components.test.tsx, tools/app/app/components/StateSelector.tsx, tools/app/app/locales/en/translation.json
StateSelector used a combination of mui and joy style.
=> Bugfix: Workflow transition menu sticks around

tools/app/app/api/templates/route.tsx, tools/app/app/components/modals/NewCardModal.tsx, tools/app/app/lib/api/types.ts, tools/data-handler/src/containers/template.ts, tools/data-handler/src/interfaces/project-interfaces.ts, tools/data-handler/src/show.ts, tools/data-handler/test/command-handler.test.ts, tools/data-handler/test/template.test.ts, tools/data-handler/test/test-data/valid/decision-records/.cards/local/templates/decision/template.json, tools/schema/template-schema.json
I used "description" instead of "templateDescription". Since we are already dealing with templates, I do not think the "template" in the variable name adds any clarity.  Description, displayName and category are optional
=> Add displayName, description and category to template schema

tools/app/app/components/modals/MetadataModal.tsx, tools/app/app/locales/en/translation.json, tools/data-handler/src/interfaces/project-interfaces.ts, tools/data-handler/src/transition.ts, tools/data-handler/test/command-handler.test.ts, tools/schema/card-base-schema.json
Added lastTransitioned to card metadata. It is updated when a card is transitioned.
=> Added lastTransitioned to card metadata

tools/app/app/api/cards/[key]/route.tsx, tools/app/app/components/FieldEditor.tsx, tools/app/app/components/MetadataView.tsx, tools/app/app/locales/en/translation.json
add 'none'-option for enum/boolean and use null rather than empty string
=> INTDEV-380 Allow null values via UI

tools/data-handler/src/containers/project.ts, tools/data-handler/src/interfaces/project-interfaces.ts, tools/data-handler/test/command-handler.test.ts, tools/data-handler/test/edit.test.ts, tools/schema/card-base-schema.json
cards have a lastUpdated field, which is set everytime a change is made
=> INTDEV-271 Add lastUpdated timestamp

README.adoc, TRADEMARK.adoc
Added trademark to root of the project and mention of it in README-file
=> Add trademark

tools/app/__tests__/components.test.tsx, tools/app/app/cards/[key]/edit/page.tsx, tools/app/app/cards/[key]/page.tsx, tools/app/app/cards/layout.tsx, tools/app/app/components/ContentToolbar.tsx, tools/app/app/components/TreeMenu.tsx, tools/app/app/components/modals/AddAttachmentModal.tsx, tools/app/app/components/modals/DeleteModal.tsx, tools/app/app/components/modals/NewCardModal.tsx, tools/app/app/lib/hooks/redux.ts, tools/app/app/lib/hooks/utils.ts, tools/app/app/lib/slices/pageState.ts, tools/app/app/lib/store.ts, tools/app/app/locales/en/translation.json
Uses browser beforeUnload event if user tries to refresh / leave page. I also wrote a wrapper for next's useRouter hook, which prevents navigation within the site
=> Warn the user if they are about to navigate away from a card that has unsaved changes

examples/decision-records/.cards/local/linktypes/.schema, tools/cli/src/index.ts, tools/data-handler/src/command-handler.ts, tools/data-handler/src/containers/project.ts, tools/data-handler/src/create.ts, tools/data-handler/src/interfaces/project-interfaces.ts, tools/data-handler/src/remove.ts, tools/data-handler/src/show.ts, tools/data-handler/test/command-handler.test.ts, tools/data-handler/test/show.test.ts, tools/data-handler/test/test-data/valid/decision-records/.cards/local/linktypes/.schema, tools/data-handler/test/test-data/valid/decision-records/.cards/local/linktypes/test.json, tools/data-handler/test/test-data/valid/minimal/.cards/local/linktypes/.schema, tools/schema/card-base-schema.json, tools/schema/cardtree-directory-schema.json, tools/schema/link-type-schema.json
Added support for links as described in https://cyberismo.atlassian.net/browse/INTDEV-16
Created 6 commands:
- cyberismo create linktype <name>
- cyberismo show linktype <name>
- cyberismo show linktypes
- cyberismo remove linktype <name>
- cyberismo create link <source card key> <destination card key> <linktype name> [link description]
- cyberismo remove link <source card key> <destination card key> <linktype name> [link description]
=> Support for links

package-lock.json, tools/app/app/api/linktypes/route.tsx, tools/app/app/cards/[key]/edit/page.tsx, tools/app/app/cards/[key]/page.tsx, tools/app/app/components/ContentArea.tsx, tools/app/app/components/ContentToolbar.tsx, tools/app/app/components/modals/GenericConfirmModal.tsx, tools/app/app/components/modals/index.ts, tools/app/app/lib/api/actions/index.ts, tools/app/app/lib/api/actions/link.ts, tools/app/app/lib/api/card.ts, tools/app/app/lib/api/linktypes.ts, tools/app/app/lib/api/types.ts, tools/app/app/lib/definitions.ts, tools/app/app/lib/swr.ts, tools/app/app/lib/utils.ts, tools/app/app/locales/en/translation.json, tools/app/package.json, tools/data-handler/src/create.ts, tools/data-handler/src/remove.ts, tools/data-handler/test/command-handler.test.ts
Added UI support for links:
- Links can be added
- Links can be removed
- Links are hidden if there is no links
=> Add UI support for links

.github/dependabot.yml
The YAML has wrong number of whitespaces which makes it incorrect.
=> Fix dependabot YAML-file

package-lock.json, tools/app/app/components/modals/MoveCardModal.tsx, tools/app/package.json, tools/cli/package.json
Make ESLint work from all tools (cli, d-h, app).
=> Fix dependencies: Make ESLint work from all tools

tools/app/app/components/modals/NewCardModal.tsx
This PR adds categories to app's new card modal.
=> INTDEV-396 Use template categories in the create dialog

tools/data-handler/src/containers/template.ts
Ensure that template container is set correctly when it is from a module.
=> INTDEV-395 Fix container name for templates from modules

examples/decision-records/.cards/local/templates/decision/template.json, examples/decision-records/.cards/local/templates/simplepage/template.json, tools/data-handler/src/containers/project.ts, tools/data-handler/src/create.ts, tools/data-handler/src/interfaces/project-interfaces.ts, tools/data-handler/test/command-handler.test.ts, tools/data-handler/test/template.test.ts, tools/data-handler/test/test-data/invalid/invalid-card-has-wrong-state/.cards/local/templates/decision/template.json, tools/data-handler/test/test-data/invalid/invalid-card-has-wrong-state/.cards/local/templates/empty/template.json, tools/data-handler/test/test-data/invalid/invalid-card-has-wrong-state/.cards/local/templates/simplepage/template.json, tools/data-handler/test/test-data/invalid/invalid-cardsconfig.json/.cards/local/templates/decision/template.json, tools/data-handler/test/test-data/invalid/invalid-cardsconfig.json/.cards/local/templates/simplepage/template.json, tools/data-handler/test/test-data/invalid/missing-cardroot/.cards/templates/test-template/template.json, tools/data-handler/test/test-data/invalid/missing-cardsconfig.json/.cards/local/templates/decision/template.json, tools/data-handler/test/test-data/invalid/missing-cardsconfig.json/.cards/local/templates/simplepage/template.json, tools/data-handler/test/test-data/invalid/no-.schema-in-.cards-workflows/.cards/local/templates/simplepage/template.json, tools/data-handler/test/test-data/test-template.json, tools/data-handler/test/test-data/valid/decision-records/.cards/local/templates/decision/template.json, tools/data-handler/test/test-data/valid/decision-records/.cards/local/templates/empty/template.json, tools/data-handler/test/test-data/valid/decision-records/.cards/local/templates/simplepage/template.json, tools/data-handler/test/test-data/valid/minimal/.cards/local/templates/test-template/template.json, tools/schema/template-schema.json
Removed all occurrences of namePrompt/buttonLabel
=> INTDEV-394 remove buttonLabel and namePrompt

tools/app/app/api/cards/[key]/route.tsx, tools/app/app/cards/[key]/page.tsx, tools/app/app/cards/layout.tsx, tools/app/app/lib/swr.ts
Handles cases such as card not found, project empty, wrong path etc.
=> INTDEV-425: Print API request error responses in content area

tools/data-handler/src/project-settings.ts, tools/data-handler/src/rename.ts
`save()` function is asynchronous, but it is not `awaited` in `setCardPrefix`. 
Fix the async function calling.
=> Asynchorous call is not 'await'ed

tools/data-handler/src/validate.ts
Noticed this while improving validation in general. 
In some cases, if there is a problem with JSON schema and metadata, the errors are printed to `stderr`. 
Use an array of errors, and handle in CLI what to do with the errors (like other validation errors are currently handled).
=> Validation: Use array of errors instead of 'console.error()'

tools/data-handler/test/calculate.test.ts
Added a few simple tests and also a test for a the full query.
Note: Clingo-parser.test.ts contains more detailed tests for the actual parser
=> Improve testing for calculations

tools/data-handler/src/containers/template.ts, tools/data-handler/src/interfaces/project-interfaces.ts, tools/data-handler/src/show.ts, tools/data-handler/test/show.test.ts, tools/data-handler/test/template.test.ts
Ensure that all 'show' types return values are handled similarly.
=> INTDEV-481 Ensure that 'show' works similarly for all resource types

tools/data-handler/src/validate.ts
Validate that `alwaysVisibleFields` and `optionallyVisibleFields` contain fieldTypes that exist in the project.
Additionally, remove duplicates from returned validation errors (all validation errors, not just these) - as issue with shared resource can be reported multiple times.
=> INTDEV-462 Validate 'always' and 'optionally' visible fields

package-lock.json, tools/app/app/cards/layout.tsx, tools/app/app/components/ContentArea.tsx, tools/app/app/components/TreeMenu.tsx, tools/app/app/globals.css, tools/app/package.json
- Enable tree view items to be expanded without navigation
- Implement resizable tree view panel via react-resizable-panels
- Add optional progress chip to tree view
- Improve tree menu elements look&feel
=> INTDEV-392: Tree view improvements

tools/data-handler/src/command-handler.ts
Cyberismo app will now try multiple ports starting from 3000 if this port is already taken.
=> INTDEV-347 Try multiple ports upon app start

tools/data-handler/src/calculate.ts, tools/data-handler/test/command-handler-import.test.ts, tools/data-handler/test/test-data/valid/decision-records/.cards/local/reports/testReport/.schema
Split this away from INTDEV-468 and fix it separately.
=> INTDEV-489 Ensure that calculation folders are created

tools/data-handler/src/calculate.ts
Collect calculations from modules also.
=> INTDEV-496 Include calculations from all imported modules

tools/data-handler/src/command-handler.ts
Let's make the port user selectable instead.
=> Revert "INTDEV-347 Try multiple ports upon app start (#114)"

tools/app/app/cards/[key]/edit/page.tsx, tools/app/app/components/ContentArea.tsx, tools/app/app/components/EditableField.tsx, tools/app/app/components/MetadataView.tsx, tools/app/app/locales/en/translation.json
One issue with preview persists, I'll wait for #194 to get merged
=> Show card key / card type in metadata view

content/defaultReport/.schema, tools/data-handler/test/command-handler-create.test.ts
Creating new report now uses the new .schema format. 
Added some basic unit tests to 'create report' functionality.
=> INTDEV-513 Create report with correct .schema format

tools/data-handler/src/interfaces/adoc.ts, tools/data-handler/src/interfaces/macros.ts, tools/data-handler/src/types/queries.ts, tools/data-handler/src/utils/random.ts
There were few missing copyright comment blocks in the source files.
=> Add missing copyright blocks

tools/app/app/components/TreeMenu.tsx
- Progress chip placement to right
- Update colors
- Hide status circle if progress present
=> Update treeview design

tools/app/app/cards/[key]/edit/page.tsx, tools/app/app/locales/en/translation.json
Lingering issues from INTDEV-467 and INTDEV-522
=> Add delete confirmation & fix build warnings

tools/data-handler/src/calculate.ts
This is related to INTDEV-496. The change was reverted by INTDEV-501.
=> Include calculations from modules too

package-lock.json, tools/data-handler/package.json, tools/data-handler/test/command-handler-create.test.ts
I ended up creating a stub for calculate in the create command. I did also try putting a manual delay to the handleNewCards function without the stub and I didn't have any issues for some reason(which was the initial concern)
=> INTDEV-458 create stub for calculate

tools/app/__tests__/api.test.ts, tools/app/__tests__/utils.test.ts, tools/app/app/lib/utils.ts, tools/app/tsconfig.json
Additional tests for API routes and utils
=> INTDEV-521 improve test coverage

calculations/common/main.lp, tools/data-handler/src/calculate.ts, tools/schema/cardTreeDirectorySchema.json
Separated imports.lp to cardTree.lp and resourceImports.lp. Also updated main.lp to import these new files
=> INTDEV-448 separate imports.lp to two files

calculations/queries/card.lp, tools/data-handler/src/calculate.ts, tools/data-handler/src/utils/clingo-parser.ts, tools/data-handler/test/utils/clingo-parser.test.ts
Added all improvements as in the ticket. I didn't yet use them on the UI.
=> INTDEV-460 Added improvements for calculations

tools/data-handler/src/calculate.ts
Added mutex to all methods, which do not use another mutex protected method
=> Add mutex to all calculate methods

.gitignore, package-lock.json, tools/app/app/components/ContentArea.tsx, tools/app/next.config.mjs, tools/data-handler/package.json, tools/data-handler/src/calculate.ts, tools/data-handler/src/containers/project/project-paths.ts, tools/data-handler/src/containers/template.ts, tools/data-handler/src/export.ts, tools/data-handler/src/import.ts, tools/data-handler/src/utils/log-utils.ts
Added a pino logger. The log file is generated under the install location in the logs folder
Behaviour in environments:
Test:
- stdout: prints anything above or at info or process.env.LOG_LEVEL if defined
Development:
- stdout: prints anything above or at debug or process.env.LOG_LEVEL if defined
- File logging: adds all logs to a file(including trace) or process.env.LOG_LEVEL if defined
Production(cli):
- File logging: adds all logs to a file(including trace) or process.env.LOG_LEVEL if defined
I went through the console.log calls, but almost all seem to be for cli. I used trace for clingo related logging
=> INTDEV-455 add logger

tools/app/app/components/ContentArea.tsx, tools/app/app/locales/en/translation.json, tools/app/cypress/e2e/app.cy.ts
- Two separate collapsible sections in sidebar
- Fix also TOC title to match designs
=> INTDEV-537: Updated UI for policy checks

tools/data-handler/src/move.ts, tools/data-handler/test/command-handler-move.test.ts
In data-handler, prevent card being moved to itself. 
Earlier, when this was done, the operation was successful and as last sub-operation 'source' is deleted, so this led to card being deleted. 
Additionally, prevent 'root' from being moved. Earlier it would complain that 'root' is not found from the project.
=> INTDEV-529 Prevent card moving to under itself

calculations/common/queryLanguage.lp, calculations/queries/card.lp, tools/app/__tests__/components.test.tsx, tools/app/__tests__/utils.test.ts, tools/app/app/cards/[key]/edit/page.tsx, tools/app/app/components/ContentArea.tsx, tools/app/app/locales/en/translation.json, tools/data-handler/src/types/queries.ts, tools/data-handler/src/utils/clingo-parser.ts, tools/data-handler/test/calculate.test.ts, tools/data-handler/test/utils/clingo-parser.test.ts
Added Notifications to app: general info/note shown to user, e.g. next steps to complete card process 
- Get notifications in card query
- Show UI element in sidebar
This PR also changes the TestSuite/TestCase fields used in policy checks to be Category/Title
=> INTDEV-539: Notifications

tools/app/package.json
=> Run app cypress tests with production build

tools/data-handler/test/command-handler-create.test.ts, tools/data-handler/test/command-handler-import.test.ts
Improve unit tests.
Add checks that resources were actually created.
Add test that imports and creates a resource using resource from imported module.
=> Add unit tests to ensure resources are created and imports work

tools/data-handler/src/containers/project.ts, tools/data-handler/src/move.ts, tools/data-handler/test/command-handler-rank.test.ts, tools/data-handler/test/test-data/valid/decision-records/.cards/local/templates/simplepage/c/decision_3/index.json
Add full support to re-rank, re-balance, or setting first rank for template cards.
Module template cards cannot be affected.
=> INTDEV-546 Support ranking template cards

tools/data-handler/src/containers/project/resource-collector.ts, tools/data-handler/src/show.ts, tools/data-handler/src/utils/file-utils.ts, tools/data-handler/test/0_validate.test.ts, tools/data-handler/test/command-handler-show.test.ts, tools/data-handler/test/utils/file-utils.test.ts
Hide file extension when using Resources in CLI / App.
=> INTDEV-593 Hide file extensions in resource handling

tools/cli/src/index.ts, tools/data-handler/src/command-handler.ts, tools/data-handler/src/create.ts, tools/data-handler/src/import.ts, tools/data-handler/src/interfaces/project-interfaces.ts, tools/data-handler/src/remove.ts, tools/data-handler/src/show.ts, tools/data-handler/test/command-handler-create.test.ts, tools/data-handler/test/command-handler-import.test.ts, tools/data-handler/test/command-handler-remove.test.ts, tools/data-handler/test/command-handler-show.test.ts, tools/data-handler/test/test-data/valid-real.csv, tools/data-handler/test/test-data/valid/decision-records/.cards/local/templates/decision/c/decision_1/index.json, tools/data-handler/test/test-data/valid/decision-records/cardRoot/decision_5/index.json
Added support for the following commands:
cyberismo create label <cardId>
cyberismo remove label <cardId> [label name]
cyberismo show labels
=> INTDEV-541 Add support for labels in cli

tools/app/app/components/modals/NewCardModal.tsx
Adds a loading indicator when the user creates a new card using the modal.
=> INTDEV-667 Add loading indicator to create card modal

tools/data-handler/src/containers/template.ts
Current implementation, fetches ALL project card for each instantiated template card. 
Only the root level cards are needed as potential siblings (needed for ranking). 
This only affects situation where cards are instantiated to root level of project (ie. parent card is not defined)
=> INTDEV-690  When creating cards, fetch only root level project cards as siblings

tools/data-handler/src/containers/card-container.ts
Re-write 'find' and 'collect' implementations of card-container base class to use `readdir` recursion instead of our own.
While the performance is about the same, the implementation is smoother and we don't have to pass a parameter where to collect values, but can use return value only.
=> INTDEV-691 Use readdir's recursion when using find or collect from containers

tools/data-handler/src/containers/project/resource-collector.ts, tools/data-handler/src/utils/file-utils.ts
Previously, module-resources were collected multiple times. 
Also, `CommandManager` is actually initialised twice per CLI command, so also local resources are collected twice. 
Add functionality that resources are collected only once. Note that this is just a collection of what resource names and paths are in the project. It does not fix accessing resource's metadata file multiple times. 
Additionally, provide a better `getFilesSync` function that does not use `lstatSync `.
=> INTDEV-674 Read module resources only once 

tools/app/app/cards/[key]/edit/page.tsx
Preview mode was crashing, since we were trying to render ContentArea in preview mode, before we had the data.
=> INTDEV-684 Fix preview crash

tools/data-handler/src/containers/project.ts
Make `listCardIds()` process container cards (project, all templates) parallel in their own promises. 
Also, add all found cards in one call to `Set` instead of adding one-by-one.
=> INTDEV-690 Parallel version of listCardIds()

tools/data-handler/src/rename.ts
Once resources have been renamed, use conversion map and try to find remaining references from certain files (`*.adoc`. `*.json`, `*.hbs` and `*.lp`) and change these references. 
**Note** that this renames also "document-like" names in `*.lp` files (e.g. `cisms_task` --> `new-name_task`).
=> INTDEV-719, INTDEV-720: Fix project renaming issues

tools/data-handler/src/validate.ts
Small optimisation to 'validate' command - each validated resource is read only once from file system.
Validation is always started from scratch (all cached `Maps` are cleared), then if a resource is needed and it is not already cached in a `Map` it is read from disk and cached to it. 
This leads to skipping ~3500 unnecessary file reads with current `main` of `module-isms-essentials`. 
With my Mac, this drops the validation command taking ~390-400ms to ~250-260ms. 
It was measured that with Windows - the same repo - the performance increase is from 1.4s to 0.7s. 
This original idea was to explore if we need the resource-cache in the future. In validation it is easy to test, since the operation is contained to one function call.  These improvements quite clearly indicate that building a …
=> INTDEV-588 Only read resources once when validating project

package.json, pnpm-lock.yaml, tools/cli/package.json, tools/data-handler/package.json
We were using a globally installed eslint, instead started using eslint package already installed in the project
=> Use eslint from project

tools/app/app/components/AppToolbar.tsx, tools/app/app/locales/en/translation.json
Current button looks like this
=> INTDEV-757 Improve create new card button UI

tools/app/app/components/TreeMenu.tsx, tools/app/app/components/modals/MoveCardModal.tsx
I removed the title from the modal, I think it should not be there
=> INTDEV-767 Remove project title from move card tree menu

tools/app/app/components/ContentArea.tsx, tools/app/app/components/ContentToolbar.tsx, tools/app/app/components/StateSelector.tsx, tools/app/app/components/modals/DeleteModal.tsx, tools/app/app/components/modals/MoveCardModal.tsx
Added spinners. The logic works via the useCard hook, meaning that any updates puts a spinner on all elements that use.
=> INTDEV-683 add spinners

calculations/common/queryLanguage.lp, tools/app/app/cards/[key]/edit/page.tsx, tools/app/app/components/ContentArea.tsx, tools/app/app/components/EditableField.tsx, tools/app/app/components/FieldEditor.tsx, tools/app/app/components/MetadataView.tsx, tools/app/app/locales/en/translation.json, tools/data-handler/src/types/queries.ts, tools/data-handler/src/utils/clingo-parser.ts, tools/data-handler/test/utils/clingo-parser.test.ts
Added an option to include a link to a field in policy check failures
=> INTDEV-714 option to include a link to a field in policy check failures

tools/app/app/cards/[key]/edit/page.tsx, tools/app/app/cards/[key]/page.tsx, tools/app/app/cards/layout.tsx, tools/app/app/lib/api/card.ts, tools/app/app/lib/hooks/utils.ts
Added a way to easily add keyboard shortcuts. Also added a few simple shortcuts:
Home -> First top-most card
c -> create new card modal
esc in edit --> cancel
e -> edit card
=> INTDEV-754 Add keyboard shortcuts

tools/data-handler/src/commands/calculate.ts
Put query files into a cache once they are needed. This should lower unnecessary file reads a little.
=> INTDEV-804 Cache calculation query files

tools/app/app/components/MetadataView.tsx
This currently contains fix for the first issue of INTDEV-776. Because of the stale-while-revalidate model, we populated the form default values using the stale data. Even if the default values are changed, react-hook-form does not reset the form. Now we reset the form when ever the data changes for the metadata.
The downside is that if you now make a change on the background and the app revalidates the data(in other words makes a request) and the value has changed, current changes are also lost. This is not a problem in the current model as changes do not happen randomly, but in a multi-user version this needs to be considered.
=> INTDEV-776 always overwrite value if defaultvalue changes

.github/workflows/build-and-test-windows.yml, .github/workflows/build-and-test.yml, .npmrc, package.json
=> INTDEV-785 Require certain nodeJS version

tools/app/cypress/e2e/app.cy.ts, tools/app/src/components/CardContextMenu.tsx, tools/app/src/components/MetadataView.tsx, tools/app/src/components/modals/DeleteModal.tsx, tools/app/src/lib/api/card.ts, tools/app/src/lib/slices/card.ts, tools/app/src/lib/store.ts, tools/app/src/locales/en/translation.json, tools/app/src/pages/card-edit.tsx
Logic is now simpler:
- if any field is touched, the dialog will be shown.
- If you start typing a label, but don't press the "+"-button, it will not trigger the dialog.
=> INTDEV-755 INTDEV-591 adjust page leave dialog

tools/app/src/routes.ts
This will redirect `/cards/{anykey}.html` to `/cards/{anykey}`
=> INTDEV-824 redirect a cards route with .html to the same url without .html ending

pnpm-lock.yaml, tools/app/package.json
To get rid of security issues: 
https://github.com/CyberismoCom/cyberismo/security/dependabot/29
https://github.com/CyberismoCom/cyberismo/security/dependabot/28
update react-router to 7.5.2.
=> Update react-router to 7.5.2

tools/data-handler/src/containers/project.ts, tools/data-handler/src/containers/project/project-paths.ts, tools/data-handler/src/module-manager.ts
Before you needed to update dependency modules separately. This meant that for example, if you'd M1, M2 and M3 as dependencies, you'd first update each of these (and their dependencies) first before you'd update your main project.
Now, each dependency (and all of the dependency hierarchy) is updated with one `update-modules` command. The command first investigates which modules need to be updated, by collecting the dependencies of the project, then for each dependency collects their dependencies and so forth, until the whole dependency hierarchy has been collected. Then, duplicates (by prefix) are removed. The final list is then either copied (file-based dependency) or cloned into `.temp` and updated as before.
**Limitation**
If there are multiple dependency entries collected, but they …
=> INTDEV-826 Update module dependencies automatically

pnpm-lock.yaml, tools/app/package.json
Update to vite version to close this: https://github.com/CyberismoCom/cyberismo/security/dependabot/30
=> Update vite to fix security vulnerability

.github/workflows/codeql-analysis.yml
Use custom CodeQL analyser, as the default tries to scan for C++ and Python.
Default scanning has been tuned off.
=> Add custom CodeQL analysis file

tools/data-handler/src/command-handler.ts
Calc run did not work, because we the file as a filepath instead of reading it.
=> Fix: Calc run does not work after C-api

tools/app/src/pages/card-edit.tsx, tools/backend/src/routes/cards.ts
Checking for empty strings resulted to being stuck in the loading state
=> INTDEV-829 Fix: only check for null/undefines

tools/backend/src/index.ts
I ended putting this to backend allthough it could be a feature of the CLI
=> INTDEV-825 support multiple instances

tools/app/cypress/e2e/app.cy.ts, tools/app/src/components/ContentToolbar.tsx
Disabled the button on the condition and added a test
=> INTDEV-808 Disable create link button, if there is only 1 card

tools/app/__tests__/utils.test.ts, tools/app/src/components/ContentArea.tsx, tools/app/src/components/modals/EditLinkModal.tsx, tools/app/src/lib/utils.ts
=> INTDEV-752 Hide cards in linkform if link already exists

tools/app/cypress/e2e/app.cy.ts, tools/app/src/components/MetadataView.tsx, tools/app/src/locales/en/translation.json
Last updated now shows up in metadata. Also e2e test for it
=> INTDEV-669 show last updated

tools/app/cypress.config.ts, tools/cli/test/cli.test.ts
Change the module imports to use git-import instead of file-import in various tests.
=> Change the tests to use git URLs for module imports

tools/app/__tests__/utils.test.ts, tools/app/src/components/ContentArea.tsx, tools/app/src/components/macros/CreateCards.tsx, tools/app/src/components/modals/NewCardModal.tsx, tools/app/src/lib/api/card.ts, tools/app/src/lib/utils.ts, tools/app/src/locales/en/translation.json, tools/backend/src/routes/cards.ts, tools/data-handler/src/command-handler.ts, tools/data-handler/src/commands/create.ts, tools/data-handler/src/commands/import.ts, tools/data-handler/src/macros/createCards/index.ts, tools/data-handler/src/macros/graph/index.ts, tools/data-handler/src/macros/index.ts, tools/data-handler/src/macros/report/index.ts, tools/data-handler/src/macros/scoreCard/index.ts, tools/data-handler/test/macros/index.test.ts, tools/schema/macros/createCardsMacroSchema.json
Links will be created for all top level cards and a message will be shown that tells how many links have been created or not(so no mention which as it would not fit to the notification). Maybe we'd need to create some kind possibility to open more detailed version of the notifications. Most common reason to fail would be attempting to create a link which does not support the given cardtypes.
=> INTDEV-830 create link in create cards macro

.github/workflows/changesets.yml
I copied the CI from pnpm docs, but seems like pnpm version was not specified. Also adjusted nodeJS version
=> Add pnpm version to CI

package.json
=> publish all but app

Dockerfile, pnpm-lock.yaml, tools/cli/package.json, tools/cli/src/index.ts, tools/data-handler/package.json, tools/data-handler/src/command-handler.ts, tools/data-handler/src/commands/import.ts, tools/data-handler/src/index.ts, tools/data-handler/src/interfaces/project-interfaces.ts, tools/data-handler/src/module-manager.ts, tools/data-handler/test/module-manager.test.ts
This is drop-in replacement for `isomorphic-git`. 
No additional new features were intended to be implemented, but looks like SSH already works (importing needs a slight adjustment).
Should we somehow ensure that git client is installed? Maybe.
=> INTDEV-860 Switch to simple-git when cloning modules

tools/assets/package.json, tools/backend/package.json, tools/cli/package.json, tools/data-handler/package.json
Test publish to make sure CI works
=> Bump to 0.0.7

tools/data-handler/src/module-manager.ts
Earlier, the implementation was using hard-coded 'main' as assumed default branch of the project.
The new implementation holds a cache of [URL, default branch] values that is updated with correct default branch value
after cloning without a branch information. This avoids making a slow git operation separately to deduce the default branch. 
It is theoretically possible that the import and update commands only use actual branches, which means that the default branch is never updated. Which is not a problem, we use the default branch information only when comparing If the updated modules are "the same". If this would lead to an error, user can easily see that the code does not understand his "branch" definition as same as default branch, and user can then adjust the `cardsConfig.json` file …
=> INTDEV-876 Use default branch name when handling git branches

tools/data-handler/src/macros/xref/index.ts, tools/data-handler/test/macros/index.test.ts
I used link instead of xref so I changed link to xref
=> INTDEV-747

tools/node-clingo/package.json, tools/node-clingo/src/function_handlers.cc, tools/node-clingo/src/function_handlers.h, tools/node-clingo/src/helpers.cc, tools/node-clingo/src/helpers.h, tools/node-clingo/test/solve.test.ts
Added `resourcePrefix`, `resourceType` and `resourceIdentifier` functions
=> INTDEV-780 Add resource prefix/type/identifier functions

tools/app/src/components/modals/svgViewerModal.tsx, tools/app/src/locales/en/translation.json
Improved way to use links. Try it out. This should now
- Not activate links if any dragging is detected
- Navigate to links if there's no dragging detected
=> INTDEV-873 Improve SVG viewer link functionality

tools/assets/package.json, tools/backend/package.json, tools/cli/package.json, tools/data-handler/package.json
=> Release 0.0.9

tools/app/src/components/ConfigMenu.tsx, tools/app/src/lib/utils.ts, tools/app/src/pages/configuration/resource.tsx
Adds highlighting for the selected resource in config editor. Also opens treemenu so that the selected resource is visible during refreshes
=> ITNDEV-974 Add highlighting for selected resource

tools/app/src/components/config-editors/BaseEditor.tsx
The ticket was initially about the tree, which was already scrollable, but I think that was a mistake. I made the content scrollable in config editor.
=> INTDEV-982 Add scroll to config editor

package.json, scripts/release.mjs, tools/assets/package.json, tools/backend/package.json, tools/cli/package.json, tools/data-handler/package.json
Release version 0.0.10. This PR contains version bump changes for release v0.0.10.
=> Release v0.0.10

.github/workflows/build-cyberismo-app-image.yml, scripts/release.mjs, tools/assets/package.json, tools/backend/package.json, tools/cli/package.json, tools/data-handler/package.json
Release version 0.0.11. This PR contains version bump changes for release 0.0.11.
=> Release v0.0.11

tools/cli/src/index.ts, tools/data-handler/test/command-handler-remove.test.ts, tools/data-handler/test/command-handler-show.test.ts
Move the default URL location from feature branch to `main` branch.
=> Switch to actual default hub URL

pnpm-lock.yaml, tools/backend/package.json
This fixes https://github.com/CyberismoCom/cyberismo/security/dependabot/43
=> SECURITY FIX: Bump Hono to 4.9.7

tools/assets/package.json, tools/backend/package.json, tools/cli/package.json, tools/data-handler/package.json
Release version 0.0.12. This PR contains version bump changes for release 0.0.12.
=> Release v0.0.12
